-- ============================================
-- Script: Eliminacion de Todos los Objetos
-- Proyecto: SHM - Sistema de Honorarios Medicos
-- ============================================
-- Descripcion: Este script elimina todas las vistas, tablas y secuencias
--              del esquema SHM_DEV para permitir recrear la base de datos
--              desde cero.
--
-- Orden de ejecucion:
--   1. Eliminar Foreign Keys (para evitar errores de dependencia)
--   2. Eliminar Vistas
--   3. Eliminar Tablas
--   4. Eliminar Secuencias
--
-- Autor: ADG Systems
-- Fecha: 2026-01-31
-- ============================================

-- ALTER SESSION SET CONTAINER = XEPDB1;
-- CONNECT shm_dev/DevPass123@//localhost:1521/XEPDB1;

SET SERVEROUTPUT ON;

DECLARE
    v_count NUMBER;
BEGIN
    DBMS_OUTPUT.PUT_LINE('============================================');
    DBMS_OUTPUT.PUT_LINE('Iniciando eliminacion de objetos SHM...');
    DBMS_OUTPUT.PUT_LINE('============================================');
END;
/

-- ============================================
-- SECCION 1: ELIMINAR FOREIGN KEYS
-- ============================================
-- Eliminar primero las FK para evitar errores de dependencia

BEGIN
    FOR c IN (SELECT constraint_name, table_name
              FROM user_constraints
              WHERE constraint_type = 'R'
              AND table_name LIKE 'SHM_%')
    LOOP
        EXECUTE IMMEDIATE 'ALTER TABLE ' || c.table_name || ' DROP CONSTRAINT ' || c.constraint_name;
        DBMS_OUTPUT.PUT_LINE('FK eliminada: ' || c.constraint_name || ' de ' || c.table_name);
    END LOOP;
END;
/

-- ============================================
-- SECCION 2: ELIMINAR VISTAS
-- ============================================

-- Vista SHM_TABLA_DETALLE_VW
BEGIN
    EXECUTE IMMEDIATE 'DROP VIEW SHM_TABLA_DETALLE_VW';
    DBMS_OUTPUT.PUT_LINE('Vista eliminada: SHM_TABLA_DETALLE_VW');
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN -- ORA-00942: table or view does not exist
            RAISE;
        END IF;
END;
/

-- ============================================
-- SECCION 3: ELIMINAR TABLAS
-- ============================================
-- Orden: Primero tablas hijas, luego tablas padre

-- Tablas con FK (hijas)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SHM_SEG_ROL_OPCION CASCADE CONSTRAINTS'; DBMS_OUTPUT.PUT_LINE('Tabla eliminada: SHM_SEG_ROL_OPCION'); EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SHM_ARCHIVO_COMPROBANTE CASCADE CONSTRAINTS'; DBMS_OUTPUT.PUT_LINE('Tabla eliminada: SHM_ARCHIVO_COMPROBANTE'); EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SHM_TABLA_DETALLE CASCADE CONSTRAINTS'; DBMS_OUTPUT.PUT_LINE('Tabla eliminada: SHM_TABLA_DETALLE'); EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SHM_ENTIDAD_CUENTA_BANCO CASCADE CONSTRAINTS'; DBMS_OUTPUT.PUT_LINE('Tabla eliminada: SHM_ENTIDAD_CUENTA_BANCO'); EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SHM_PRODUCCION CASCADE CONSTRAINTS'; DBMS_OUTPUT.PUT_LINE('Tabla eliminada: SHM_PRODUCCION'); EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SHM_SEG_USUARIO CASCADE CONSTRAINTS'; DBMS_OUTPUT.PUT_LINE('Tabla eliminada: SHM_SEG_USUARIO'); EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

-- Tablas padre (sin dependencias o ya eliminadas las FK)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SHM_SEG_OPCION CASCADE CONSTRAINTS'; DBMS_OUTPUT.PUT_LINE('Tabla eliminada: SHM_SEG_OPCION'); EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SHM_SEG_ROL CASCADE CONSTRAINTS'; DBMS_OUTPUT.PUT_LINE('Tabla eliminada: SHM_SEG_ROL'); EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SHM_ARCHIVO CASCADE CONSTRAINTS'; DBMS_OUTPUT.PUT_LINE('Tabla eliminada: SHM_ARCHIVO'); EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SHM_BANCO CASCADE CONSTRAINTS'; DBMS_OUTPUT.PUT_LINE('Tabla eliminada: SHM_BANCO'); EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SHM_BITACORA CASCADE CONSTRAINTS'; DBMS_OUTPUT.PUT_LINE('Tabla eliminada: SHM_BITACORA'); EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SHM_SEDE CASCADE CONSTRAINTS'; DBMS_OUTPUT.PUT_LINE('Tabla eliminada: SHM_SEDE'); EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SHM_TABLA CASCADE CONSTRAINTS'; DBMS_OUTPUT.PUT_LINE('Tabla eliminada: SHM_TABLA'); EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SHM_ENTIDAD_MEDICA CASCADE CONSTRAINTS'; DBMS_OUTPUT.PUT_LINE('Tabla eliminada: SHM_ENTIDAD_MEDICA'); EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SHM_PARAMETRO CASCADE CONSTRAINTS'; DBMS_OUTPUT.PUT_LINE('Tabla eliminada: SHM_PARAMETRO'); EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SHM_EMAIL_LOG CASCADE CONSTRAINTS'; DBMS_OUTPUT.PUT_LINE('Tabla eliminada: SHM_EMAIL_LOG'); EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

-- ============================================
-- SECCION 4: ELIMINAR SECUENCIAS
-- ============================================

BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SHM_ARCHIVO_SEQ'; DBMS_OUTPUT.PUT_LINE('Secuencia eliminada: SHM_ARCHIVO_SEQ'); EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SHM_ARCHIVO_COMPROBANTE_SEQ'; DBMS_OUTPUT.PUT_LINE('Secuencia eliminada: SHM_ARCHIVO_COMPROBANTE_SEQ'); EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SHM_BANCO_SEQ'; DBMS_OUTPUT.PUT_LINE('Secuencia eliminada: SHM_BANCO_SEQ'); EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SHM_BITACORA_SEQ'; DBMS_OUTPUT.PUT_LINE('Secuencia eliminada: SHM_BITACORA_SEQ'); EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SHM_ENTIDAD_CUENTA_BANCO_SEQ'; DBMS_OUTPUT.PUT_LINE('Secuencia eliminada: SHM_ENTIDAD_CUENTA_BANCO_SEQ'); EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SHM_ENTIDAD_MEDICA_SEQ'; DBMS_OUTPUT.PUT_LINE('Secuencia eliminada: SHM_ENTIDAD_MEDICA_SEQ'); EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SHM_PRODUCCION_SEQ'; DBMS_OUTPUT.PUT_LINE('Secuencia eliminada: SHM_PRODUCCION_SEQ'); EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SHM_SEDE_SEQ'; DBMS_OUTPUT.PUT_LINE('Secuencia eliminada: SHM_SEDE_SEQ'); EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SHM_SEG_OPCION_SEQ'; DBMS_OUTPUT.PUT_LINE('Secuencia eliminada: SHM_SEG_OPCION_SEQ'); EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SHM_SEG_ROL_SEQ'; DBMS_OUTPUT.PUT_LINE('Secuencia eliminada: SHM_SEG_ROL_SEQ'); EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SHM_SEG_ROL_OPCION_SEQ'; DBMS_OUTPUT.PUT_LINE('Secuencia eliminada: SHM_SEG_ROL_OPCION_SEQ'); EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SHM_SEG_USUARIO_SEQ'; DBMS_OUTPUT.PUT_LINE('Secuencia eliminada: SHM_SEG_USUARIO_SEQ'); EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SHM_TABLA_SEQ'; DBMS_OUTPUT.PUT_LINE('Secuencia eliminada: SHM_TABLA_SEQ'); EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SHM_TABLA_DETALLE_SEQ'; DBMS_OUTPUT.PUT_LINE('Secuencia eliminada: SHM_TABLA_DETALLE_SEQ'); EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SHM_PARAMETRO_SEQ'; DBMS_OUTPUT.PUT_LINE('Secuencia eliminada: SHM_PARAMETRO_SEQ'); EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SHM_EMAIL_LOG_SEQ'; DBMS_OUTPUT.PUT_LINE('Secuencia eliminada: SHM_EMAIL_LOG_SEQ'); EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/

-- ============================================
-- SECCION 5: VERIFICACION
-- ============================================

DECLARE
    v_tables NUMBER;
    v_sequences NUMBER;
    v_views NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_tables FROM user_tables WHERE table_name LIKE 'SHM_%';
    SELECT COUNT(*) INTO v_sequences FROM user_sequences WHERE sequence_name LIKE 'SHM_%';
    SELECT COUNT(*) INTO v_views FROM user_views WHERE view_name LIKE 'SHM_%';

    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('============================================');
    DBMS_OUTPUT.PUT_LINE('RESUMEN DE OBJETOS RESTANTES:');
    DBMS_OUTPUT.PUT_LINE('============================================');
    DBMS_OUTPUT.PUT_LINE('Tablas SHM_*:     ' || v_tables);
    DBMS_OUTPUT.PUT_LINE('Secuencias SHM_*: ' || v_sequences);
    DBMS_OUTPUT.PUT_LINE('Vistas SHM_*:     ' || v_views);
    DBMS_OUTPUT.PUT_LINE('============================================');

    IF v_tables = 0 AND v_sequences = 0 AND v_views = 0 THEN
        DBMS_OUTPUT.PUT_LINE('TODOS LOS OBJETOS ELIMINADOS EXITOSAMENTE');
    ELSE
        DBMS_OUTPUT.PUT_LINE('ATENCION: Algunos objetos no fueron eliminados');
    END IF;

    DBMS_OUTPUT.PUT_LINE('============================================');
END;
/

-- Mostrar objetos restantes (si los hay)
SELECT 'TABLA' AS TIPO, TABLE_NAME AS NOMBRE FROM USER_TABLES WHERE TABLE_NAME LIKE 'SHM_%'
UNION ALL
SELECT 'SECUENCIA', SEQUENCE_NAME FROM USER_SEQUENCES WHERE SEQUENCE_NAME LIKE 'SHM_%'
UNION ALL
SELECT 'VISTA', VIEW_NAME FROM USER_VIEWS WHERE VIEW_NAME LIKE 'SHM_%';

COMMIT;

-- ============================================
-- INSTRUCCIONES DE USO
-- ============================================
-- Para ejecutar este script:
--
-- Opcion 1: SQL*Plus
--   sqlplus shm_dev/DevPass123@//localhost:1521/XEPDB1 @00_drop_all_objects.sql
--
-- Opcion 2: Docker
--   docker exec -it oracle-practice-db sqlplus shm_dev/DevPass123@//localhost:1521/XEPDB1 @/path/00_drop_all_objects.sql
--
-- Despues de ejecutar este script, puede recrear los objetos con:
--   1. 02_create_tables.sql
--   2. 03_create_sequence.sql
--   3. 04_create_view.sql
--   4. 05_insert_data.sql (datos iniciales)
-- ============================================
