
-- Table Asegura que no se repitan los CODIGO_ENTIDAD activos en la tabla SHM_ENTIDAD_MEDICA

CREATE UNIQUE INDEX SHM_ENTIDAD_MEDICA_UK_COD ON SHM_ENTIDAD_MEDICA (
    CASE WHEN ACTIVO = 1 THEN CODIGO_ENTIDAD ELSE NULL END
);

-- Table Asegura que no se repitan los CODIGO activos en la tabla SHM_SEDE
CREATE UNIQUE INDEX SHM_SEDE_UK_COD ON SHM_SEDE (
    CASE WHEN ACTIVO = 1 THEN CODIGO ELSE NULL END
);

