-- ============================================
-- Script: Creación de Tablas
-- ============================================

-- ALTER SESSION SET CONTAINER = XEPDB1;
-- CONNECT shm_dev/DevPass123@//localhost:1521/XEPDB1;

/*
Created: 2/01/2026
Modified: 18/01/2026
Model: Oracle 12c Release 1
Database: Oracle 12c
*/


-- Create tables section -------------------------------------------------

-- Table SHM_ENTIDAD_MEDICA

CREATE TABLE SHM_ENTIDAD_MEDICA(
  ID_ENTIDAD_MEDICA Number NOT NULL,
  CODIGO_ENTIDAD Varchar2(100 ) NOT NULL,
  RAZON_SOCIAL Varchar2(300 ),
  RUC Varchar2(20 ),
  TIPO_ENTIDAD_MEDICA Varchar2(5 ),
  TELEFONO Varchar2(20 ),
  CELULAR Varchar2(20 ),
  DIRECCION NVarchar2(300),
  CODIGO_ACREEDOR Varchar2(20 ),
  CODIGO_CORRENTISTA Varchar2(20 ),
  GUID_REGISTRO Varchar2(100 ),
  ACTIVO Number(1),
  ID_CREADOR Number,
  FECHA_CREACION Date,
  ID_MODIFICADOR Number,
  FECHA_MODIFICACION Date
)
/

-- Add keys for table SHM_ENTIDAD_MEDICA

ALTER TABLE SHM_ENTIDAD_MEDICA ADD CONSTRAINT PK_SHM_ENTIDAD_MEDICA PRIMARY KEY (ID_ENTIDAD_MEDICA)
/

-- Table SHM_ENTIDAD_CUENTA_BANCO

CREATE TABLE SHM_ENTIDAD_CUENTA_BANCO(
  ID_CUENTA_BANCO Number NOT NULL,
  ID_ENTIDAD_MEDICA Number,
  ID_BANCO Number,
  CUENTA_CORRIENTE Varchar2(100 ),
  CUENTA_CCI Varchar2(100 ),
  MONEDA Varchar2(3 ),
  GUID_REGISTRO Varchar2(100 ),
  ACTIVO Number(1),
  ID_CREADOR Number,
  FECHA_CREACION Date,
  ID_MODIFICADOR Number,
  FECHA_MODIFICACION Date
)
/

-- Add keys for table SHM_ENTIDAD_CUENTA_BANCO

ALTER TABLE SHM_ENTIDAD_CUENTA_BANCO ADD CONSTRAINT PK_SHM_ENTIDAD_CUENTA_BANCO PRIMARY KEY (ID_CUENTA_BANCO)
/

-- Table SHM_SEG_USUARIO

CREATE TABLE SHM_SEG_USUARIO(
  ID_USUARIO Number NOT NULL,
  TIPO_USUARIO Char(1 ) NOT NULL,
  LOGIN Varchar2(100 ) NOT NULL,
  PASSWORD Varchar2(255 ) NOT NULL,
  EMAIL Varchar2(100 ),
  NUMERO_DOCUMENTO Varchar2(20 ),
  NOMBRES Varchar2(100 ),
  APELLIDO_PATERNO Varchar2(100 ),
  APELLIDO_MATERNO Varchar2(100 ),
  TELEFONO Varchar2(20 ),
  CELULAR Varchar2(10 ),
  CARGO Varchar2(120 ),
  ID_ENTIDAD_MEDICA Number,
  ID_ROL Number,
  TOKEN_RECUPERACION Varchar2(100 ),
  FECHA_EXPIRACION_TOKEN Timestamp,
  GUID_REGISTRO Varchar2(100 ) NOT NULL,
  ACTIVO Number(1) NOT NULL,
  ID_CREADOR Number NOT NULL,
  FECHA_CREACION Date NOT NULL,
  ID_MODIFICADOR Number,
  FECHA_MODIFICACION Date
)
/

-- Add keys for table SHM_SEG_USUARIO

ALTER TABLE SHM_SEG_USUARIO ADD CONSTRAINT PK_SHM_SEG_USUARIO PRIMARY KEY (ID_USUARIO)
/

-- Table SHM_PRODUCCION

CREATE TABLE SHM_PRODUCCION(
	ID_PRODUCCION Number NOT NULL,
	ID_SEDE Number,
	ID_ENTIDAD_MEDICA Number,
	CODIGO_PRODUCCION Varchar2(8 ),
	NUMERO_PRODUCCION	VARCHAR2(10),
	TIPO_ENTIDAD_MEDICA	VARCHAR2(2),
	TIPO_PRODUCCION Varchar2(5 ),
	TIPO_MEDICO Varchar2(2 ),
	TIPO_RUBRO Varchar2(5 ),
	DESCRIPCION Varchar2(200 ),
	PERIODO Varchar2(10 ),
  FECHA_PRODUCCION DATE,
	ESTADO_PRODUCCION Varchar2(30 ),
	MTO_CONSUMO Number,
	MTO_DESCUENTO Number,
	MTO_SUBTOTAL Number,
	MTO_RENTA Number,
	MTO_IGV Number,
	MTO_TOTAL Number(15,2),
	TIPO_COMPROBANTE Varchar2(2 ),
	CONCEPTO Varchar2(200 ),
	FECHA_LIMITE Date,
	SERIE Varchar2(4 ),
	NUMERO Varchar2(10 ),
	FECHA_EMISION Date,
	GLOSA Varchar2(300 ),
	ESTADO_COMPROBANTE Varchar2(20 ),
	FACTURA_FECHA_SOLICITUD DATE,
	FACTURA_FECHA_ENVIO DATE,
	FACTURA_FECHA_ACEPTACION DATE,
	FACTURA_FECHA_PAGO DATE,
	NUMERO_LIQUIDACION	VARCHAR2(10),
	CODIGO_LIQUIDACION	VARCHAR2(20),
	PERIODO_LIQUIDACION	VARCHAR2(10),
	ESTADO_LIQUIDACION	VARCHAR2(10),
	FECHA_LIQUIDACION	DATE,
	DESCRIPCION_LIQUIDACION	VARCHAR2(300),
	ESTADO Varchar2(30 ),
  ID_CUENTA_BANCO Number,
	GUID_REGISTRO Varchar2(100 ),
	ACTIVO Number(1),
	ID_CREADOR Number,
	FECHA_CREACION Date,
	ID_MODIFICADOR Number,
	FECHA_MODIFICACION Date
)
/

-- Add keys for table SHM_PRODUCCION

ALTER TABLE SHM_PRODUCCION ADD CONSTRAINT PK_SHM_PRODUCCION PRIMARY KEY (ID_PRODUCCION)
/

-- Table SHM_SEDE

CREATE TABLE SHM_SEDE(
  ID_SEDE Number NOT NULL,
  ID_CORPORACION Number,
  CODIGO Varchar2(5 ),
  NOMBRE Varchar2(100 ),
  RUC Char(20 ),
  DIRECCION Varchar2(300 ),
  GUID_REGISTRO Varchar2(100 ),
  ACTIVO Number(1),
  ID_CREADOR Number,
  FECHA_CREACION Date,
  ID_MODIFICADOR Number,
  FECHA_MODIFICACION Date
)
/

-- Add keys for table SHM_SEDE

ALTER TABLE SHM_SEDE ADD CONSTRAINT PK_SHM_SEDE PRIMARY KEY (ID_SEDE)
/

-- Table SHM_BITACORA

CREATE TABLE SHM_BITACORA(
  ID_BITACORA Number NOT NULL,
  ENTIDAD Varchar2(100 ),
  ID_ENTIDAD NUMBER,
  ACCION Varchar2(100 ),
  DESCRIPCION Varchar2(500 ),
  FECHA_ACCION DATE,
  GUID_REGISTRO Varchar2(100 ),
  ACTIVO Number(1),
  ID_CREADOR Number,
  FECHA_CREACION Date,
  ID_MODIFICADOR Number,
  FECHA_MODIFICACION Date
)
/

-- Add keys for table SHM_BITACORA

ALTER TABLE SHM_BITACORA ADD CONSTRAINT PK_SHM_BITACORA PRIMARY KEY (ID_BITACORA)
/

-- Table SHM_BANCO

CREATE TABLE SHM_BANCO(
  ID_BANCO Number NOT NULL,
  CODIGO_BANCO Varchar2(10 ),
  NOMBRE_BANCO Varchar2(100 ),
  GUID_REGISTRO Varchar2(100 ),
  ACTIVO Number(1),
  ID_CREADOR Number,
  FECHA_CREACION Date,
  ID_MODIFICADOR Number,
  FECHA_MODIFICACION Date
)
/

-- Add keys for table SHM_BANCO

ALTER TABLE SHM_BANCO ADD CONSTRAINT PK_SHM_BANCO PRIMARY KEY (ID_BANCO)
/

-- Table SHM_ARCHIVO

CREATE TABLE SHM_ARCHIVO(
  ID_ARCHIVO Number NOT NULL,
  TIPO_ARCHIVO Varchar2(200 ),
  NOMBRE_ORIGINAL Varchar2(255 ),
  NOMBRE_ARCHIVO Varchar2(100 ),
  EXTENSION Varchar2(5 ),
  TAMANO Number,
  RUTA Varchar2(100 ),
  CONTENIDO_ARCHIVO BLOB,
  TIPO_ALMACENAMIENTO VARCHAR2(20),
  GUID_REGISTRO Varchar2(100 ),
  ACTIVO Number(1),
  ID_CREADOR Number,
  FECHA_CREACION Date,
  ID_MODIFICADOR Number,
  FECHA_MODIFICACION Date
)
/

-- Add keys for table SHM_ARCHIVO

ALTER TABLE SHM_ARCHIVO ADD CONSTRAINT PK_SHM_ARCHIVO PRIMARY KEY (ID_ARCHIVO)
/

-- Table SHM_TABLA

CREATE TABLE SHM_TABLA(
  ID_TABLA Number NOT NULL,
  CODIGO Varchar2(50 ),
  DESCRIPCION Varchar2(250 ),
  ACTIVO Number(1),
  GUID_REGISTRO Varchar2(100 ),
  ID_CREADOR Number,
  FECHA_CREACION Date,
  ID_MODIFICADOR Number,
  FECHA_MODIFICACION Date
)
/

-- Add keys for table SHM_TABLA

ALTER TABLE SHM_TABLA ADD CONSTRAINT PK_SHM_TABLA PRIMARY KEY (ID_TABLA)
/

-- Table SHM_TABLA_DETALLE

CREATE TABLE SHM_TABLA_DETALLE(
  ID_TABLA Number NOT NULL,
  ID_TABLA_DETALLE Number NOT NULL,
  CODIGO Varchar2(100 ),
  DESCRIPCION Varchar2(100 ),
  ORDEN Number,
  GUID_REGISTRO Varchar2(100 ),
  ACTIVO Number(1),
  ID_CREADOR Integer,
  FECHA_CREACION Date,
  ID_MODIFICADOR Integer,
  FECHA_MODIFICACION Date
)
/

-- Add keys for table SHM_TABLA_DETALLE

ALTER TABLE SHM_TABLA_DETALLE ADD CONSTRAINT PK_SHM_TABLA_DETALLE PRIMARY KEY (ID_TABLA,ID_TABLA_DETALLE)
/

-- Table SHM_ARCHIVO_COMPROBANTE

CREATE TABLE SHM_ARCHIVO_COMPROBANTE(
  ID_ARCHIVO_COMPROBANTE Number NOT NULL,
  ID_PRODUCCION Number,
  ID_ARCHIVO Number,
  TIPO_ARCHIVO Varchar2(30 ),
  DESCRIPCION Varchar2(100 ),
  GUID_REGISTRO Varchar2(100 ),
  ACTIVO Number(1),
  ID_CREADOR Number,
  FECHA_CREACION Date,
  ID_MODIFICADOR Number,
  FECHA_MODIFICACION Date
)
/

-- Add keys for table SHM_ARCHIVO_COMPROBANTE

ALTER TABLE SHM_ARCHIVO_COMPROBANTE ADD CONSTRAINT PK_SHM_ARCHIVO_COMPROBANTE PRIMARY KEY (ID_ARCHIVO_COMPROBANTE)
/

-- Table SHM_SEG_OPCION

CREATE TABLE SHM_SEG_OPCION(
  ID_OPCION Number NOT NULL,
  NOMBRE Varchar2(100 ) NOT NULL,
  URL Varchar2(255 ),
  ICONO Varchar2(255 ),
  ORDEN Number,
  ID_OPCION_PADRE Number,
  GUID_REGISTRO Varchar2(100 ),
  ACTIVO Number(1),
  ID_CREADOR Number,
  FECHA_CREACION Date,
  ID_MODIFICADOR Number,
  FECHA_MODIFICACION Date
)
/

-- Add keys for table SHM_SEG_OPCION

ALTER TABLE SHM_SEG_OPCION ADD CONSTRAINT PK_SHM_SEG_OPCION PRIMARY KEY (ID_OPCION)
/

-- Table SHM_SEG_ROL

CREATE TABLE SHM_SEG_ROL(
  ID_ROL Number NOT NULL,
  CODIGO Varchar2(100 ) NOT NULL,
  DESCRIPCION Varchar2(100 ) NOT NULL,
  GUID_REGISTRO Varchar2(100 ),
  ACTIVO Number(1),
  ID_CREADOR Number,
  FECHA_CREACION Date,
  ID_MODIFICADOR Number,
  FECHA_MODIFICACION Date
)
/

-- Add keys for table SHM_SEG_ROL

ALTER TABLE SHM_SEG_ROL ADD CONSTRAINT PK_SHM_SEG_ROL PRIMARY KEY (ID_ROL)
/

-- Table SHM_SEG_ROL_OPCION

CREATE TABLE SHM_SEG_ROL_OPCION(
  ID_ROL Number NOT NULL,
  ID_OPCION Number NOT NULL,
  GUID_REGISTRO Varchar2(100 ),
  ACTIVO Number(1),
  ID_CREADOR Number,
  FECHA_CREACION Date,
  ID_MODIFICADOR Number,
  FECHA_MODIFICACION Date
)
/

-- Add keys for table SHM_SEG_ROL_OPCION

ALTER TABLE SHM_SEG_ROL_OPCION ADD CONSTRAINT PK_SHM_SEG_ROL_OPCION PRIMARY KEY (ID_ROL,ID_OPCION)
/

-- Table SHM_PARAMETRO

CREATE TABLE SHM_PARAMETRO(
  ID_PARAMETRO Number NOT NULL,
  CODIGO Varchar2(100 ),
  VALOR Varchar2(512 ),
  DESCRIPCION Varchar2(1024),
  GUID_REGISTRO Varchar2(100 ),
  ACTIVO Number(1),
  ID_CREADOR Number,
  FECHA_CREACION Date,
  ID_MODIFICADOR Number,
  FECHA_MODIFICACION Date
)
/

-- Add keys for table SHM_PARAMETRO

ALTER TABLE SHM_PARAMETRO ADD CONSTRAINT PK_SHM_PARAMETRO PRIMARY KEY (ID_PARAMETRO)
/

-- Table SHM_EMAIL_LOG

CREATE TABLE SHM_EMAIL_LOG (
    ID_EMAIL_LOG         NUMBER NOT NULL,
    EMAIL_DESTINO        VARCHAR2(200) NOT NULL,
    NOMBRE_DESTINO       VARCHAR2(200),
    ASUNTO               VARCHAR2(500) NOT NULL,
    TIPO_EMAIL           VARCHAR2(50) NOT NULL,
    CONTENIDO            CLOB,
    ES_HTML              NUMBER(1) DEFAULT 0,
    ESTADO               VARCHAR2(20) NOT NULL,
    MENSAJE_ERROR        VARCHAR2(4000),
    ID_USUARIO           NUMBER,
    ID_ENTIDAD_MEDICA    NUMBER,
    ENTIDAD_REFERENCIA   VARCHAR2(50),
    ID_REFERENCIA        NUMBER,
    SERVIDOR_SMTP        VARCHAR2(100),
    IP_ORIGEN            VARCHAR2(50),
    GUID_REGISTRO        VARCHAR2(100) NOT NULL,
    ACTIVO               NUMBER(1) DEFAULT 1,
    ID_CREADOR           NUMBER,
    FECHA_CREACION       DATE DEFAULT SYSDATE,
    ID_MODIFICADOR       NUMBER,
    FECHA_MODIFICACION   DATE
)
/

-- Add keys for table SHM_EMAIL_LOG

ALTER TABLE SHM_EMAIL_LOG ADD CONSTRAINT PK_SHM_EMAIL_LOG PRIMARY KEY (ID_EMAIL_LOG)
/

-- Table SHM_SEG_USUARIO_SEDE

CREATE TABLE SHM_SEG_USUARIO_SEDE(
  ID_USUARIO Number NOT NULL,
  ID_SEDE Number NOT NULL,
  GUID_REGISTRO Varchar2(100 ),
  ES_ULTIMA_SEDE Number(1,0),
  ACTIVO Number(1,0),
  ID_CREADOR Number,
  FECHA_CREACION Date
)
/

-- Add keys for table SHM_SEG_USUARIO_SEDE

ALTER TABLE SHM_SEG_USUARIO_SEDE ADD CONSTRAINT PK_SHM_SEG_USUARIO_SEDE PRIMARY KEY (ID_USUARIO,ID_SEDE)
/


-- Table SHM_ORDEN_PAGO

CREATE TABLE SHM_ORDEN_PAGO(
  ID_ORDEN_PAGO Number NOT NULL,
  ID_SEDE Number NOT NULL,
  ID_BANCO Number NOT NULL,
  NUMERO_ORDEN_PAGO Varchar2(20 ),
  FECHA_GENERACION Date,
  ESTADO Varchar2(30 ),
  MTO_CONSUMO_ACUM Number,
  MTO_DESCUENTO_ACUM Number,
  MTO_SUBTOTAL_ACUM Number,
  MTO_RENTA_ACUM Number,
  MTO_IGV_ACUM Number,
  MTO_TOTAL_ACUM Number,
  CANT_COMPROBANTES Number,
  CANT_LIQUIDACIONES Number,
  COMENTARIOS Varchar2(1000 ),
  GUID_REGISTRO Varchar2(100 ),
  ACTIVO Number(1),
  ID_CREADOR Number,
  FECHA_CREACION Date,
  ID_MODIFICADOR Number,
  FECHA_MODIFICACION Date
)
/

-- Add keys for table SHM_ORDEN_PAGO

ALTER TABLE SHM_ORDEN_PAGO ADD CONSTRAINT PK_SHM_ORDEN_PAGO PRIMARY KEY (ID_ORDEN_PAGO)
/

-- Table SHM_ORDEN_PAGO_PRODUCCION

CREATE TABLE SHM_ORDEN_PAGO_PRODUCCION(
  ID_ORDEN_PAGO_PRODUCCION Number NOT NULL,
  ID_ORDEN_PAGO Number NOT NULL,
  ID_PRODUCCION Number NOT NULL,
  GUID_REGISTRO Varchar2(100 ),
  ACTIVO Number(1),
  ID_CREADOR Number,
  FECHA_CREACION Date,
  ID_MODIFICADOR Number,
  FECHA_MODIFICACION Date
)
/

-- Add keys for table SHM_ORDEN_PAGO_PRODUCCION

ALTER TABLE SHM_ORDEN_PAGO_PRODUCCION ADD CONSTRAINT PK_SHM_ORDEN_PAGO_PRODUCCION PRIMARY KEY (ID_ORDEN_PAGO_PRODUCCION)
/

-- Table SHM_ORDEN_PAGO_LIQUIDACION

CREATE TABLE SHM_ORDEN_PAGO_LIQUIDACION(
  ID_ORDEN_PAGO_LIQUIDACION Number NOT NULL,
  ID_ORDEN_PAGO Number,
  NUMERO_LIQUIDACION Varchar2(20 ),
  CODIGO_LIQUIDACION Varchar2(20 ),
  MTO_CONSUMO_ACUM Number,
  MTO_DESCUENTO_ACUM Number,
  MTO_SUBTOTAL_ACUM Number,
  MTO_RENTA_ACUM Number,
  MTO_IGV_ACUM Number,
  MTO_TOTAL_ACUM Number,
  CANT_COMPROBANTES Number,
  COMENTARIOS Varchar2(1000 ),
  GUID_REGISTRO Varchar2(100 ),
  ACTIVO Number(1),
  ID_CREADOR Number,
  FECHA_CREACION Date,
  ID_MODIFICADOR Number,
  FECHA_MODIFICACION Date
)
/

-- Add keys for table SHM_ORDEN_PAGO_LIQUIDACION

ALTER TABLE SHM_ORDEN_PAGO_LIQUIDACION ADD CONSTRAINT PK_SHM_ORDEN_PAGO_LIQUIDACION PRIMARY KEY (ID_ORDEN_PAGO_LIQUIDACION)
/


-- Table SHM_ORDEN_PAGO_APROBACION

CREATE TABLE SHM_ORDEN_PAGO_APROBACION(
  ID_ORDEN_PAGO_APROBACION Number NOT NULL,
  ID_ORDEN_PAGO Number NOT NULL,
  ID_PERFIL_APROBACION NOT Number,
  ESTADO Varchar2(30 ) NOT NULL,
  ID_USUARIO_APROBADOR Number,
  FECHA_APROBACION Date,
  ORDEN Number(3) NOT NULL,
  GUID_REGISTRO Varchar2(100 ) NOT NULL,
  ACTIVO Number(1) NOT NULL,
  ID_CREADOR Number NOT NULL,
  FECHA_CREACION Date NOT NULL,
  ID_MODIFICADOR Number,
  FECHA_MODIFICACION Date
)
/

-- Add keys for table SHM_ORDEN_PAGO_APROBACION

ALTER TABLE SHM_ORDEN_PAGO_APROBACION ADD CONSTRAINT PK_SHM_ORDEN_PAGO_APROBACION PRIMARY KEY (ID_ORDEN_PAGO_APROBACION)
/


-- Table SHM_PERFIL_APROBACION

CREATE TABLE SHM_PERFIL_APROBACION(
  ID_PERFIL_APROBACION Number NOT NULL,
  GRUPO_FLUJO_TRABAJO Varchar2(100 ) NOT NULL,
  CODIGO Varchar2(30 ) NOT NULL,
  DESCRIPCION Varchar2(100 ) NOT NULL,
  NIVEL Varchar2(30 ) NOT NULL,
  ORDEN Number(3) NOT NULL,
  GUID_REGISTRO Varchar2(100 ) NOT NULL,
  ACTIVO Number(1) NOT NULL,
  ID_USUARIO_CREADOR Number NOT NULL,
  FECHA_CREACION Date NOT NULL
)
/

-- Add keys for table SHM_PERFIL_APROBACION

ALTER TABLE SHM_PERFIL_APROBACION ADD CONSTRAINT PK_SHM_PERFIL_APROBACION PRIMARY KEY (ID_PERFIL_APROBACION)
/

-- Table SHM_PERFIL_APROBACION_USUARIO

CREATE TABLE SHM_PERFIL_APROBACION_USUARIO(
  ID_PERFIL_APROBACION Number NOT NULL,
  ID_USUARIO Number NOT NULL,
  ID_SEDE Number
)
/

-- Add keys for table SHM_PERFIL_APROBACION_USUARIO

ALTER TABLE SHM_PERFIL_APROBACION_USUARIO ADD CONSTRAINT PK_SHM_PERFIL_APROBACION_USUA PRIMARY KEY (ID_PERFIL_APROBACION,ID_USUARIO)
/

-- Create foreign keys (relationships) section ------------------------------------------------- 

ALTER TABLE SHM_ENTIDAD_CUENTA_BANCO ADD CONSTRAINT FK_SHM_ENTIDAD_CUENTA_BANC_01 FOREIGN KEY (ID_ENTIDAD_MEDICA) REFERENCES SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA)
/

ALTER TABLE SHM_SEG_USUARIO ADD CONSTRAINT FK_SHM_USUARIO_ENTIDAD_MED_01 FOREIGN KEY (ID_ENTIDAD_MEDICA) REFERENCES SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA)
/

ALTER TABLE SHM_PRODUCCION ADD CONSTRAINT FK_SHM_PRODUCCION_04 FOREIGN KEY (ID_SEDE) REFERENCES SHM_SEDE (ID_SEDE)
/

ALTER TABLE SHM_PRODUCCION ADD CONSTRAINT FK_SHM_PRODUCCION_05 FOREIGN KEY (ID_ENTIDAD_MEDICA) REFERENCES SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA)
/

ALTER TABLE SHM_ENTIDAD_CUENTA_BANCO ADD CONSTRAINT FK_SHM_CUENTA_BANCARIA_BANCO FOREIGN KEY (ID_BANCO) REFERENCES SHM_BANCO (ID_BANCO)
/

ALTER TABLE SHM_TABLA_DETALLE ADD CONSTRAINT FK_TABLA_DETALLE FOREIGN KEY (ID_TABLA) REFERENCES SHM_TABLA (ID_TABLA)
/

ALTER TABLE SHM_ARCHIVO_COMPROBANTE ADD CONSTRAINT FK_SHM_ARCH_COMPRO_01 FOREIGN KEY (ID_PRODUCCION) REFERENCES SHM_PRODUCCION (ID_PRODUCCION)
/

ALTER TABLE SHM_ARCHIVO_COMPROBANTE ADD CONSTRAINT FK_SHM_ARCH_COMPRO_02 FOREIGN KEY (ID_ARCHIVO) REFERENCES SHM_ARCHIVO (ID_ARCHIVO)
/

ALTER TABLE SHM_SEG_USUARIO ADD CONSTRAINT FK_SHM_USUARIO_ROL FOREIGN KEY (ID_ROL) REFERENCES SHM_SEG_ROL (ID_ROL)
/

ALTER TABLE SHM_SEG_ROL_OPCION ADD CONSTRAINT FK_SHM_ROL_OPCION_02 FOREIGN KEY (ID_ROL) REFERENCES SHM_SEG_ROL (ID_ROL)
/

ALTER TABLE SHM_SEG_ROL_OPCION ADD CONSTRAINT FK_SHM_ROL_OPCION_01 FOREIGN KEY (ID_OPCION) REFERENCES SHM_SEG_OPCION (ID_OPCION)
/

ALTER TABLE SHM_SEG_USUARIO_SEDE ADD CONSTRAINT FK_SEG_USUARIO_SEDE FOREIGN KEY (ID_USUARIO) REFERENCES SHM_SEG_USUARIO (ID_USUARIO)
/

ALTER TABLE SHM_SEG_USUARIO_SEDE ADD CONSTRAINT FK_SEDE_USUARIO FOREIGN KEY (ID_SEDE) REFERENCES SHM_SEDE (ID_SEDE)
/

ALTER TABLE SHM_ORDEN_PAGO_PRODUCCION ADD CONSTRAINT FK_SHM_ORDEN_PAGO_PROD_01 FOREIGN KEY (ID_ORDEN_PAGO) REFERENCES SHM_ORDEN_PAGO (ID_ORDEN_PAGO)
/

ALTER TABLE SHM_ORDEN_PAGO_PRODUCCION ADD CONSTRAINT FK_SHM_ORDEN_PAGO_PROD_02 FOREIGN KEY (ID_PRODUCCION) REFERENCES SHM_PRODUCCION (ID_PRODUCCION)
/

ALTER TABLE SHM_ORDEN_PAGO_LIQUIDACION ADD CONSTRAINT FK_SHM_ORDE_PAGO_LIQ_01 FOREIGN KEY (ID_ORDEN_PAGO) REFERENCES SHM_ORDEN_PAGO (ID_ORDEN_PAGO)
/

ALTER TABLE SHM_ORDEN_PAGO ADD CONSTRAINT FK_SHM_ORDEN_PAGO_BANCO FOREIGN KEY (ID_BANCO) REFERENCES SHM_BANCO (ID_BANCO)
/

ALTER TABLE SHM_ORDEN_PAGO ADD CONSTRAINT FK_SHM_ORDEN_PAGO_SEDE FOREIGN KEY (ID_SEDE) REFERENCES SHM_SEDE (ID_SEDE)
/

ALTER TABLE SHM_ORDEN_PAGO_APROBACION ADD CONSTRAINT FK_SHM_ORDEN_PAGO_APROB FOREIGN KEY (ID_ORDEN_PAGO) REFERENCES SHM_ORDEN_PAGO (ID_ORDEN_PAGO)
/

ALTER TABLE SHM_ORDEN_PAGO_APROBACION ADD CONSTRAINT FK_SHM_ORDEN_PAGO_APROB_PERFIL FOREIGN KEY (ID_PERFIL_APROBACION) REFERENCES SHM_PERFIL_APROBACION (ID_PERFIL_APROBACION)
/

ALTER TABLE SHM_ORDEN_PAGO_APROBACION ADD CONSTRAINT FK_SHM_ORDEN_PAGO_APROB_USU FOREIGN KEY (ID_USUARIO_APROBADOR) REFERENCES SHM_SEG_USUARIO (ID_USUARIO)
/

ALTER TABLE SHM_PERFIL_APROBACION_USUARIO ADD CONSTRAINT FK_SHM_PERFIL_APROBACION_01 FOREIGN KEY (ID_PERFIL_APROBACION) REFERENCES SHM_PERFIL_APROBACION (ID_PERFIL_APROBACION)
/

ALTER TABLE SHM_PERFIL_APROBACION_USUARIO ADD CONSTRAINT FK_SHM_PERFIL_APROBACION_02 FOREIGN KEY (ID_USUARIO) REFERENCES SHM_SEG_USUARIO (ID_USUARIO)
/

ALTER TABLE SHM_PERFIL_APROBACION_USUARIO ADD CONSTRAINT FK_SHM_PERFIL_APROBACION_03 FOREIGN KEY (ID_SEDE) REFERENCES SHM_SEDE (ID_SEDE)
/

COMMIT;

SELECT 'Tablas creadas exitosamente' AS mensaje FROM DUAL;

SELECT TABLE_NAME 
FROM ALL_TABLES
WHERE OWNER  = 'SHM_DEV';

