-- ============================================
-- Script: Creación de Secuencias
-- ============================================

-- ALTER SESSION SET CONTAINER = XEPDB1;
-- CONNECT shm_dev/DevPass123@//localhost:1521/XEPDB1;

CREATE SEQUENCE SHM_ARCHIVO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SHM_ARCHIVO_COMPROBANTE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SHM_BANCO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SHM_BITACORA_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SHM_ENTIDAD_CUENTA_BANCO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SHM_ENTIDAD_MEDICA_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SHM_PRODUCCION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SHM_SEDE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SHM_SEG_OPCION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SHM_SEG_ROL_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SHM_SEG_ROL_OPCION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SHM_SEG_USUARIO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SHM_TABLA_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SHM_TABLA_DETALLE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SHM_PARAMETRO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SHM_EMAIL_LOG_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SHM_ORDEN_PAGO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SHM_ORDEN_PAGO_LIQUIDACION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SHM_ORDEN_PAGO_APROBACION_SEQ START WITH 1 INCREMENT BY 1  NOCACHE NOCYCLE;

COMMIT;

SELECT 'Secuencias creadas exitosamente' AS mensaje FROM DUAL;
