-- 1 Crea Vista
-- ALTER SESSION SET CONTAINER = XEPDB1;
-- CONNECT shm_dev/DevPass123@//localhost:1521/XEPDB1;

CREATE OR REPLACE VIEW SHM_TABLA_DETALLE_VW AS
SELECT T1.CODIGO AS CODIGO_TABLA, T2.CODIGO, T2.DESCRIPCION, T2.ORDEN, T2.ACTIVO
FROM SHM_TABLA T1, SHM_TABLA_DETALLE T2
WHERE T1.ID_TABLA = T2.ID_TABLA;


CREATE VIEW SHM_TIPO_LIQUIDACION_VW
AS
SELECT TD.CODIGO, TD.DESCRIPCION
FROM SHM_TABLA_DETALLE TC, SHM_TABLA_DETALLE TD
WHERE TC.ID_TABLA = TD.ID_TABLA 
AND TC.CODIGO = 'TIPO_LIQUIDACION';

CREATE OR REPLACE VIEW SHM_TIPO_PRODUCCION_VW
AS
SELECT TD.CODIGO, TD.DESCRIPCION
FROM SHM_TABLA TC, SHM_TABLA_DETALLE TD
WHERE TC.ID_TABLA = TD.ID_TABLA 
AND TC.CODIGO = 'TIPO_PRODUCCION';

CREATE OR REPLACE VIEW SHM_TIPO_ENTIDAD_MEDICA_VW
AS
SELECT TD.CODIGO, TD.DESCRIPCION
FROM SHM_TABLA TC, SHM_TABLA_DETALLE TD
WHERE TC.ID_TABLA = TD.ID_TABLA 
AND TC.CODIGO = 'TIPO_ENTIDAD_MEDICA';