ALTER SESSION SET CONTAINER = XEPDB1;
CONNECT shm_dev/DevPass123@//localhost:1521/XEPDB1;

INSERT INTO SHM_TABLA(ID_TABLA, CODIGO, DESCRIPCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES(SHM_TABLA_DETALLE_SEQ.NEXTVAL,'TIPO_ENTIDAD_MEDICA','TIPO_ENTIDAD_MEDICA',1, SYS_GUID(),1, SYSDATE);
INSERT INTO SHM_TABLA(ID_TABLA, CODIGO, DESCRIPCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES(SHM_TABLA_DETALLE_SEQ.NEXTVAL,'TIPO_PRODUCCION','TIPO_PRODUCCION',1, SYS_GUID(),1, SYSDATE);
INSERT INTO SHM_TABLA(ID_TABLA, CODIGO, DESCRIPCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES(SHM_TABLA_DETALLE_SEQ.NEXTVAL,'TIPO_MEDICO','TIPO_MEDICO',1, SYS_GUID(),1, SYSDATE);
INSERT INTO SHM_TABLA(ID_TABLA, CODIGO, DESCRIPCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES(SHM_TABLA_DETALLE_SEQ.NEXTVAL,'TIPO_RUBRO','TIPO_RUBRO',1, SYS_GUID(),1, SYSDATE);
INSERT INTO SHM_TABLA(ID_TABLA, CODIGO, DESCRIPCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES(SHM_TABLA_DETALLE_SEQ.NEXTVAL,'TIPO_USUARIO','TIPO_USUARIO',1, SYS_GUID(),1, SYSDATE);

COMMIT;

INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(1,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'CM','Compañía medica',1, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(1,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'M','Medico',2, SYS_GUID(), 1, 1, SYSDATE);

INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(2,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'01','Crédito',1, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(2,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'02','Contado',2, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(2,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'03','Plan Familiar',3, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(2,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'04','Pronto Pago',4, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(2,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'12','Servicio de Laboratorio',5, SYS_GUID(), 1, 1, SYSDATE);

INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(3,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'01','Médico Invitado',1, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(3,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'02','Cía. Médica / Médico',2, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(3,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'03','Facturación labcore',3, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(3,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'04','Facturación Tomomedic',4, SYS_GUID(), 1, 1, SYSDATE);

INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(4,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'00','Clínica',1, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(4,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'02','Servicios',2, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(4,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'03','Todos',3, SYS_GUID(), 1, 1, SYSDATE);

INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(5,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'I','Interno',1, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(5,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'E','Externo',2, SYS_GUID(), 1, 1, SYSDATE);

COMMIT;


INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'0130','CORAL HOLDING S.A','20388232481','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'0237','TIBUMEDICAL E.I.R.L','20513596406 ','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'0248','NEUROCIRUGIA E.I.R.L.','20513676345 ','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'0349','CARDIOVASCULARES ASOCIADOS SOCIEDAD ANONIMA CERRADA','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'0555','VISIONIX E.I.R.L.','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'0573','H & S RADIOLOGOS ASOCIADOS SAC','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'0994','CARDIO TEAM CSC S.A.C','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'1176','PARPSURG E.I.R.L.','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'1179','SERVICIOS DE SALUD PAREDES Y ASOCIADOS S.A.C','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'1329','QUALAB SOCIEDAD ANONIMA CERRADA','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'3797','ESPECIALIDADES MEDICAS EDUMILY S.A.C.','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'3998','INMUNO ONCOLOGIA MOLECULAR EMPRESAINDIVIDUAL DE RESPONSABILI','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'4232','PLUS GASTRO SERVICIOS MEDICOS A & SE.I.R.L.','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'4326','GINECOLOGOPEREZ E.I.R.L.','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'4643','GYNESALUD MEDICAL SERVICES S.A.C.','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'59525','MOLINA ALMANZA MARIBEL MILAGROS','','M', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'6067','NUTRIMED E.I.R.L.','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'6482','URO SMART E.I.R.L.','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'6831','VERMEDICALSERVICE E.I.R.L.','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'77393','DREXLER RIVERO SILVANA ARLETTE','','M', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'8014','MAXIMO SALUD E.I.R.L.','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'9804','CRB CIRUGIA Y COLOPROCTOLOGIA SEGURA E.I.R.L','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'9972','YACTAYO CARDIOCENTER E.I.R.L.','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'9973','CARDIOSALUD VERASIL E.I.R.L.','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'9974','GIATHAJJO E.I.R.L.','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'9975','EQUILIBRASALUD E.I.R.L.','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'9976','CARDIOYEN S.A.C.','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'9977','RHEUMALIFE E.I.R.L.','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'9978','NEUMOLOGO LANDA E.I.R.L.','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'9979','HEH SERVICIOS Y SALUD E.I.R.L.','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'9980','ECOGASTRO E.I.R.L.','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'9982','GASTRICHEALTH E.I.R.L.','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'9983','ENDOSCOPIC SOLUTIONS E.I.R.L.','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'9985','CARMAR SERVICIOS E.I.R.L.','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'9988','DIAGNOSTICO MEDES S.A.C.S.','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'9991','NEUROMED FVW E.I.R.L.','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'9994','ARNAO Y CORRALES SERVICIOS MEDICOS ESPECIALIZADOS S.A.C.','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'9996','PEDISUR E.I.R.L.','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'9997','UROPLUS E.I.R.L.','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'A001','HEALTH & WELLNESS S.A.C.','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'A002','CENTRO ENDOCRINOMETABOLICO ESPECIALIZADO ACOSTA E.I.R.L.','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'A010','NEUROCIRUGIA AQP E.I.R.L.','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'A012','JOM SALUD E.I.R.L.','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'A014','INTERNAL MEDICINE CARE E.I.R.L.','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'A015','MENTALIZ E.I.R.L.','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'A018','MACULA Y RETINA MEDICA E.I.R.L.','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'A041','PSYCHEMEDIC E.I.R.L.','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'A042','ARTROSMEDIC E.I.R.L.','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'A043','THORALLERGY E.I.R.L.','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'A044','CARDIOLIFE GROUP E.I.R.L.','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'A064','MEDSURGICORP E.I.R.L.','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'A077','ENDO MEDICINE E.I.R.L.','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'A089','GINE MATER MEDIC E.I.R.L.','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'A093','LONGEVITA SALUD E.I.R.L.','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'A111','PACMEDICAL E.I.R.L.','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'A113','SOLUCIONES QUIRURGICAS PERUANAS E.I.R.L.','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'A129','DR. CRISTIAN FARFAN ESPEJO OTORRINOLARIN','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'A136','TRAUMATOLOGY & ORTHOPEDICS SPECIALITYCENTER E.I.R.L.','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'A143','REAL VISION: CENTRO DE PREVENCIÓN','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'A144','NENE DENTS E.I.R.L.','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'A150','CORP. CARDIOVASCULAR Y TORACICA','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'A153','NAYA PSYCHOLOGY E.I.R.L.','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'A170','SERVICIOS MEDICOS NEUROQUIRURGICOS S.A.C','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'A175','SERVICIOS NEFROLOGICOS SAN MARTIN DE POR','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'A177','ARTEA CAST E.I.R.L.','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'A218','CONFIAMED E.I.R.L.','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'A363','INVERSIONES MEDICAS AAS E.I.R.L.','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'A364','CIRUJANOS INNOVADORES GROUP E.I.R.L.','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'A372','SERVICIOS MEDICOS DIETER CUEVA YOHANN E.','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'A382','SAN HILDEGARDA E.I.R.L.','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'A386','CORDIS IESU E.I.R.L.','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'A388','CLINICA MEDICA DEL CORAZON E.I.R.L.','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'A391','CARLOS J.FINLAY E.I.R.L.','','CM', SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_ENTIDAD_MEDICA (ID_ENTIDAD_MEDICA, CODIGO_ENTIDAD, RAZON_SOCIAL, RUC, TIPO_ENTIDAD_MEDICA,  GUID_REGISTRO, ACTIVO,  ID_CREADOR, FECHA_CREACION) VALUES(SHM_ENTIDAD_MEDICA_SEQ.NEXTVAL,'A399','LIVERKIDS E.I.R.L.','','CM', SYS_GUID(), 1, 1, SYSDATE);

COMMIT;

INSERT INTO SHM_SEDE (ID_SEDE, ID_CORPORACION, CODIGO, NOMBRE, RUC, DIRECCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEDE_SEQ.NEXTVAL,1,'01','SAN PABLO','20107463705','Av. El Polo 789, Santiago de Surco, Lima',1, sys_guid(),1, SYSDATE );
INSERT INTO SHM_SEDE (ID_SEDE, ID_CORPORACION, CODIGO, NOMBRE, RUC, DIRECCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEDE_SEQ.NEXTVAL,1,'09','SAN GABRIEL','20505018509','Av. La Marina 2955, San Miguel, Lima',1, sys_guid(),1, SYSDATE );
INSERT INTO SHM_SEDE (ID_SEDE, ID_CORPORACION, CODIGO, NOMBRE, RUC, DIRECCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEDE_SEQ.NEXTVAL,1,'04','JESUS DEL NORTE','20517738701','Av. Carlos Izaguirre 153, Independencia, Lima',1, sys_guid(),1, SYSDATE );
INSERT INTO SHM_SEDE (ID_SEDE, ID_CORPORACION, CODIGO, NOMBRE, RUC, DIRECCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEDE_SEQ.NEXTVAL,1,'03','SANTA MARTHA DEL SUR','','Av. Belisario Suarez 998, SAN JUAN DE MIRAFLORES, Lima',1, sys_guid(),1, SYSDATE );
INSERT INTO SHM_SEDE (ID_SEDE, ID_CORPORACION, CODIGO, NOMBRE, RUC, DIRECCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEDE_SEQ.NEXTVAL,1,'07','SAN JUAN BAUTISTA','','Av. Proceres de la Independencia 1764, San Juan de Lurigancho, Lima',1, sys_guid(),1, SYSDATE );
INSERT INTO SHM_SEDE (ID_SEDE, ID_CORPORACION, CODIGO, NOMBRE, RUC, DIRECCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEDE_SEQ.NEXTVAL,1,'26','CERRO COLORADO','','Av. Metropolitana, con Calle 7, Cerro Colorado, Arequipa',1, sys_guid(),1, SYSDATE );
INSERT INTO SHM_SEDE (ID_SEDE, ID_CORPORACION, CODIGO, NOMBRE, RUC, DIRECCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEDE_SEQ.NEXTVAL,1,'','CLINICA SAN PABLO TRUJILLO','','Av. Husares de  Junin 690, Urb. La Merced, Trujillo',1, sys_guid(),1, SYSDATE );
INSERT INTO SHM_SEDE (ID_SEDE, ID_CORPORACION, CODIGO, NOMBRE, RUC, DIRECCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEDE_SEQ.NEXTVAL,1,'05','SAN PABLO HUARAZ','','Jr. Huaylas 172, Huaraz',1, sys_guid(),1, SYSDATE );
INSERT INTO SHM_SEDE (ID_SEDE, ID_CORPORACION, CODIGO, NOMBRE, RUC, DIRECCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEDE_SEQ.NEXTVAL,1,'13','LA ALAMEDA','','',1, sys_guid(),1, SYSDATE );
INSERT INTO SHM_SEDE (ID_SEDE, ID_CORPORACION, CODIGO, NOMBRE, RUC, DIRECCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEDE_SEQ.NEXTVAL,1,'15','LA MERCED','','',1, sys_guid(),1, SYSDATE );
INSERT INTO SHM_SEDE (ID_SEDE, ID_CORPORACION, CODIGO, NOMBRE, RUC, DIRECCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEDE_SEQ.NEXTVAL,1,'16','PRIMAVERA','','',1, sys_guid(),1, SYSDATE );
INSERT INTO SHM_SEDE (ID_SEDE, ID_CORPORACION, CODIGO, NOMBRE, RUC, DIRECCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEDE_SEQ.NEXTVAL,1,'38','DERMOESTHETIC','','',1, sys_guid(),1, SYSDATE );
INSERT INTO SHM_SEDE (ID_SEDE, ID_CORPORACION, CODIGO, NOMBRE, RUC, DIRECCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEDE_SEQ.NEXTVAL,1,'43','MEDICENTRO LOS OLIVOS','','',1, sys_guid(),1, SYSDATE );
INSERT INTO SHM_SEDE (ID_SEDE, ID_CORPORACION, CODIGO, NOMBRE, RUC, DIRECCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEDE_SEQ.NEXTVAL,1,'45','LA VICTORIA','','',1, sys_guid(),1, SYSDATE );
INSERT INTO SHM_SEDE (ID_SEDE, ID_CORPORACION, CODIGO, NOMBRE, RUC, DIRECCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEDE_SEQ.NEXTVAL,1,'','SAN PABLO LA VICTORIA','20605554505','Av. Iquitos 600, La Victoria, Lima',1, sys_guid(),1, SYSDATE );

COMMIT;

INSERT INTO SHM_SEG_ROL (ID_ROL, CODIGO, DESCRIPCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEG_ROL_SEQ.NEXTVAL,'ADMINISTRADOR_SISTEMA','Administrador del sistema',1,sys_guid() , 1 , SYSDATE);
INSERT INTO SHM_SEG_ROL (ID_ROL, CODIGO, DESCRIPCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEG_ROL_SEQ.NEXTVAL,'COMPANIA_MEDICA','Compañía médica',1,sys_guid() , 1 , SYSDATE);
INSERT INTO SHM_SEG_ROL (ID_ROL, CODIGO, DESCRIPCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEG_ROL_SEQ.NEXTVAL,'HONORARIO_MEDICO','Honorarios medicos',1,sys_guid() , 1 , SYSDATE);
INSERT INTO SHM_SEG_ROL (ID_ROL, CODIGO, DESCRIPCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEG_ROL_SEQ.NEXTVAL,'TESORERIA','Tesorería',1,sys_guid() , 1 , SYSDATE);
INSERT INTO SHM_SEG_ROL (ID_ROL, CODIGO, DESCRIPCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEG_ROL_SEQ.NEXTVAL,'APROBADOR','Aprobador',1,sys_guid() , 1 , SYSDATE);


INSERT INTO SHM_SEG_OPCION (ID_OPCION, NOMBRE, URL, ICONO, ORDEN, ID_OPCION_PADRE, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (1,'Opcion 1','','',1,0, 1,sys_guid() , 1 , SYSDATE);
INSERT INTO SHM_SEG_OPCION (ID_OPCION, NOMBRE, URL, ICONO, ORDEN, ID_OPCION_PADRE, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (2,'Opcion 2','','',2,0, 1,sys_guid() , 1 , SYSDATE);

COMMIT;

INSERT INTO SHM_SEG_ROL_OPCION (ID_ROL, ID_OPCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (1,1, 1,sys_guid() , 1 , SYSDATE);
INSERT INTO SHM_SEG_ROL_OPCION (ID_ROL, ID_OPCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (1,2, 1,sys_guid() , 1 , SYSDATE);

COMMIT;

INSERT INTO SHM_SEG_USUARIO (ID_USUARIO, TIPO_USUARIO, LOGIN, PASSWORD, EMAIL, NUMERO_DOCUMENTO, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, CELULAR, ID_ENTIDAD_MEDICA, ID_ROL, 
ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) 
VALUES (SHM_SEG_USUARIO_SEQ.NEXTVAL,'I','SYSDAMIN','123456','admin@compania.com','99988877','MANUEL ANTONIO','AAAAAA','LLLLLLLLL','9998887777',NULL,1, 
1, sys_guid(),1, SYSDATE );

COMMIT;

SELECT 'Registros insertados exitosamente' AS mensaje FROM DUAL;
