ALTER SESSION SET CONTAINER = XEPDB1;
CONNECT shm_dev/DevPass123@//localhost:1521/XEPDB1;

INSERT INTO SHM_TABLA(ID_TABLA, CODIGO, DESCRIPCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES(SHM_TABLA_SEQ.NEXTVAL,'TIPO_ENTIDAD_MEDICA','TIPO_ENTIDAD_MEDICA',1, SYS_GUID(),1, SYSDATE);
INSERT INTO SHM_TABLA(ID_TABLA, CODIGO, DESCRIPCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES(SHM_TABLA_SEQ.NEXTVAL,'TIPO_PRODUCCION','TIPO_PRODUCCION',1, SYS_GUID(),1, SYSDATE);
INSERT INTO SHM_TABLA(ID_TABLA, CODIGO, DESCRIPCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES(SHM_TABLA_SEQ.NEXTVAL,'TIPO_MEDICO','TIPO_MEDICO',1, SYS_GUID(),1, SYSDATE);
INSERT INTO SHM_TABLA(ID_TABLA, CODIGO, DESCRIPCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES(SHM_TABLA_SEQ.NEXTVAL,'TIPO_RUBRO','TIPO_RUBRO',1, SYS_GUID(),1, SYSDATE);
INSERT INTO SHM_TABLA(ID_TABLA, CODIGO, DESCRIPCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES(SHM_TABLA_SEQ.NEXTVAL,'TIPO_USUARIO','TIPO_USUARIO',1, SYS_GUID(),1, SYSDATE);
INSERT INTO SHM_TABLA(ID_TABLA, CODIGO, DESCRIPCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES(SHM_TABLA_SEQ.NEXTVAL,'ESTADO_PROCESO','ESTADO_PROCESO',1, SYS_GUID(),1, SYSDATE);

COMMIT;

INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(1,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'CM','Compañía medica',1, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(1,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'M','Medico',2, SYS_GUID(), 1, 1, SYSDATE);

INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(2,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'01','Crédito',1, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(2,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'02','Contado',2, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(2,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'03','Plan Familiar',3, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(2,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'04','Pronto Pago',4, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(2,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'12','Servicio de Laboratorio',5, SYS_GUID(), 1, 1, SYSDATE);

INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(3,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'01','Médico Invitado',1, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(3,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'02','Cía. Médica / Médico',2, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(3,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'03','Facturación labcore',3, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(3,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'04','Facturación Tomomedic',4, SYS_GUID(), 1, 1, SYSDATE);

INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(4,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'00','Clínica',1, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(4,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'02','Servicios',2, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(4,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'03','Todos',3, SYS_GUID(), 1, 1, SYSDATE);

INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(5,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'I','Interno',1, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(5,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'E','Externo',2, SYS_GUID(), 1, 1, SYSDATE);

INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(6,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'FACTURA_PENDIENTE','Factura Pendiente',1, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(6,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'FACTURA_SOLICITADA','Factura Solicitada',2, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(6,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'FACTURA_ENVIADA','Factura Enviada',3, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(6,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'FACTURA_ACEPTADA','Factura Aceptada',4, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(6,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'FACTURA_ENVIADA_HHMM','Factura Enviada a HHMM',5, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(6,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'FACTURA_LIQUIDADA','Factura Liquidada',6, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(6,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'FACTURA_ORDEN_PAGO','Factura en Orden de Pago',7, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(6,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'FACTURA_PAGADA','Factura Pagada',8, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(6,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'FACTURA_DEVUELTA','Factura Devuelta',9, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(6,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'FACTURA_ANULADA','Factura Devuelta',10, SYS_GUID(), 1, 1, SYSDATE);

COMMIT;

INSERT INTO SHM_SEDE (ID_SEDE, ID_CORPORACION, CODIGO, NOMBRE, RUC, DIRECCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEDE_SEQ.NEXTVAL,1,'01','SAN PABLO','20107463705','Av. El Polo 789, Santiago de Surco, Lima',1, sys_guid(),1, SYSDATE );
INSERT INTO SHM_SEDE (ID_SEDE, ID_CORPORACION, CODIGO, NOMBRE, RUC, DIRECCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEDE_SEQ.NEXTVAL,1,'09','SAN GABRIEL','20505018509','Av. La Marina 2955, San Miguel, Lima',1, sys_guid(),1, SYSDATE );
INSERT INTO SHM_SEDE (ID_SEDE, ID_CORPORACION, CODIGO, NOMBRE, RUC, DIRECCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEDE_SEQ.NEXTVAL,1,'04','JESUS DEL NORTE','20517738701','Av. Carlos Izaguirre 153, Independencia, Lima',1, sys_guid(),1, SYSDATE );
INSERT INTO SHM_SEDE (ID_SEDE, ID_CORPORACION, CODIGO, NOMBRE, RUC, DIRECCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEDE_SEQ.NEXTVAL,1,'03','SANTA MARTHA DEL SUR','','Av. Belisario Suarez 998, SAN JUAN DE MIRAFLORES, Lima',1, sys_guid(),1, SYSDATE );
INSERT INTO SHM_SEDE (ID_SEDE, ID_CORPORACION, CODIGO, NOMBRE, RUC, DIRECCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEDE_SEQ.NEXTVAL,1,'07','SAN JUAN BAUTISTA','','Av. Proceres de la Independencia 1764, San Juan de Lurigancho, Lima',1, sys_guid(),1, SYSDATE );
INSERT INTO SHM_SEDE (ID_SEDE, ID_CORPORACION, CODIGO, NOMBRE, RUC, DIRECCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEDE_SEQ.NEXTVAL,1,'26','CERRO COLORADO','','Av. Metropolitana, con Calle 7, Cerro Colorado, Arequipa',1, sys_guid(),1, SYSDATE );
INSERT INTO SHM_SEDE (ID_SEDE, ID_CORPORACION, CODIGO, NOMBRE, RUC, DIRECCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEDE_SEQ.NEXTVAL,1,'','CLINICA SAN PABLO TRUJILLO','','Av. Husares de  Junin 690, Urb. La Merced, Trujillo',1, sys_guid(),1, SYSDATE );
INSERT INTO SHM_SEDE (ID_SEDE, ID_CORPORACION, CODIGO, NOMBRE, RUC, DIRECCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEDE_SEQ.NEXTVAL,1,'05','SAN PABLO HUARAZ','','Jr. Huaylas 172, Huaraz',1, sys_guid(),1, SYSDATE );
INSERT INTO SHM_SEDE (ID_SEDE, ID_CORPORACION, CODIGO, NOMBRE, RUC, DIRECCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEDE_SEQ.NEXTVAL,1,'13','LA ALAMEDA','','',1, sys_guid(),1, SYSDATE );
INSERT INTO SHM_SEDE (ID_SEDE, ID_CORPORACION, CODIGO, NOMBRE, RUC, DIRECCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEDE_SEQ.NEXTVAL,1,'15','LA MERCED','','',1, sys_guid(),1, SYSDATE );
INSERT INTO SHM_SEDE (ID_SEDE, ID_CORPORACION, CODIGO, NOMBRE, RUC, DIRECCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEDE_SEQ.NEXTVAL,1,'16','PRIMAVERA','','',1, sys_guid(),1, SYSDATE );
INSERT INTO SHM_SEDE (ID_SEDE, ID_CORPORACION, CODIGO, NOMBRE, RUC, DIRECCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEDE_SEQ.NEXTVAL,1,'38','DERMOESTHETIC','','',1, sys_guid(),1, SYSDATE );
INSERT INTO SHM_SEDE (ID_SEDE, ID_CORPORACION, CODIGO, NOMBRE, RUC, DIRECCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEDE_SEQ.NEXTVAL,1,'43','MEDICENTRO LOS OLIVOS','','',1, sys_guid(),1, SYSDATE );
INSERT INTO SHM_SEDE (ID_SEDE, ID_CORPORACION, CODIGO, NOMBRE, RUC, DIRECCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEDE_SEQ.NEXTVAL,1,'45','LA VICTORIA','','',1, sys_guid(),1, SYSDATE );
INSERT INTO SHM_SEDE (ID_SEDE, ID_CORPORACION, CODIGO, NOMBRE, RUC, DIRECCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEDE_SEQ.NEXTVAL,1,'','SAN PABLO LA VICTORIA','20605554505','Av. Iquitos 600, La Victoria, Lima',1, sys_guid(),1, SYSDATE );

COMMIT;

INSERT INTO SHM_SEG_ROL (ID_ROL, CODIGO, DESCRIPCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEG_ROL_SEQ.NEXTVAL,'ADMINISTRADOR_SISTEMA','Administrador del sistema',1,sys_guid() , 1 , SYSDATE);
INSERT INTO SHM_SEG_ROL (ID_ROL, CODIGO, DESCRIPCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEG_ROL_SEQ.NEXTVAL,'COMPANIA_MEDICA','Compañía médica',1,sys_guid() , 1 , SYSDATE);
INSERT INTO SHM_SEG_ROL (ID_ROL, CODIGO, DESCRIPCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEG_ROL_SEQ.NEXTVAL,'HONORARIO_MEDICO','Honorarios medicos',1,sys_guid() , 1 , SYSDATE);
INSERT INTO SHM_SEG_ROL (ID_ROL, CODIGO, DESCRIPCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEG_ROL_SEQ.NEXTVAL,'TESORERIA','Tesorería',1,sys_guid() , 1 , SYSDATE);
INSERT INTO SHM_SEG_ROL (ID_ROL, CODIGO, DESCRIPCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEG_ROL_SEQ.NEXTVAL,'APROBADOR','Aprobador',1,sys_guid() , 1 , SYSDATE);

COMMIT;

INSERT INTO SHM_SEG_OPCION (ID_OPCION, NOMBRE, URL, ICONO, ORDEN, ID_OPCION_PADRE, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEG_OPCION_SEQ.nextval,'Principal','','',10,0, 1, RAWTOHEX(sys_guid())  , 1 , SYSDATE);
INSERT INTO SHM_SEG_OPCION (ID_OPCION, NOMBRE, URL, ICONO, ORDEN, ID_OPCION_PADRE, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEG_OPCION_SEQ.nextval,'Reportes','','',20,0, 1, RAWTOHEX(sys_guid()) , 1 , SYSDATE);
INSERT INTO SHM_SEG_OPCION (ID_OPCION, NOMBRE, URL, ICONO, ORDEN, ID_OPCION_PADRE, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEG_OPCION_SEQ.nextval,'Administración','','',90,0, 1, RAWTOHEX(sys_guid()) , 1 , SYSDATE);

COMMIT;

INSERT INTO SHM_SEG_OPCION (ID_OPCION, NOMBRE, URL, ICONO, ORDEN, ID_OPCION_PADRE, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEG_OPCION_SEQ.nextval,'Opcion 1','controller/accion1','<i class="far fa-circle nav-icon"></i>',1,(SELECT MAX(ID_OPCION) FROM SHM_SEG_OPCION WHERE NOMBRE = 'Principal' AND NVL(ID_OPCION_PADRE, 0) = 0 ), 1, RAWTOHEX(sys_guid()) , 1 , SYSDATE);
INSERT INTO SHM_SEG_OPCION (ID_OPCION, NOMBRE, URL, ICONO, ORDEN, ID_OPCION_PADRE, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEG_OPCION_SEQ.nextval,'Opcion 2','controller/accion2','<i class="far fa-circle nav-icon"></i>',2,(SELECT MAX(ID_OPCION) FROM SHM_SEG_OPCION WHERE NOMBRE = 'Principal' AND NVL(ID_OPCION_PADRE, 0) = 0 ), 1, RAWTOHEX(sys_guid()) , 1 , SYSDATE);
INSERT INTO SHM_SEG_OPCION (ID_OPCION, NOMBRE, URL, ICONO, ORDEN, ID_OPCION_PADRE, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEG_OPCION_SEQ.nextval,'Opcion 3','controller/accion3','<i class="far fa-circle nav-icon"></i>',3,(SELECT MAX(ID_OPCION) FROM SHM_SEG_OPCION WHERE NOMBRE = 'Principal' AND NVL(ID_OPCION_PADRE, 0) = 0 ), 1,sys_guid() , 1 , SYSDATE);

INSERT INTO SHM_SEG_OPCION (ID_OPCION, NOMBRE, URL, ICONO, ORDEN, ID_OPCION_PADRE, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (6,'Reporte 1','reporte/reporte1','<i class="far fa-circle nav-icon"></i>',1,(SELECT MAX(ID_OPCION) FROM SHM_SEG_OPCION WHERE NOMBRE = 'Reportes' AND NVL(ID_OPCION_PADRE, 0) = 0 ), 1, RAWTOHEX(sys_guid()) , 1 , SYSDATE);
INSERT INTO SHM_SEG_OPCION (ID_OPCION, NOMBRE, URL, ICONO, ORDEN, ID_OPCION_PADRE, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (7,'Reporte 2','reporte/reporte2','<i class="far fa-circle nav-icon"></i>',2,(SELECT MAX(ID_OPCION) FROM SHM_SEG_OPCION WHERE NOMBRE = 'Reportes' AND NVL(ID_OPCION_PADRE, 0) = 0 ), 1, RAWTOHEX(sys_guid()) , 1 , SYSDATE);

INSERT INTO SHM_SEG_OPCION (ID_OPCION, NOMBRE, URL, ICONO, ORDEN, ID_OPCION_PADRE, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEG_OPCION_SEQ.nextval,'Sedes','Sede/Index','<i class="far fa-circle nav-icon"></i>',1,(SELECT MAX(ID_OPCION) FROM SHM_SEG_OPCION WHERE NOMBRE = 'Administración' AND NVL(ID_OPCION_PADRE, 0) = 0 ), 1, RAWTOHEX(sys_guid()) , 1 , SYSDATE);
INSERT INTO SHM_SEG_OPCION (ID_OPCION, NOMBRE, URL, ICONO, ORDEN, ID_OPCION_PADRE, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEG_OPCION_SEQ.nextval,'Bancos','Banco/Index','<i class="far fa-circle nav-icon"></i>',2,(SELECT MAX(ID_OPCION) FROM SHM_SEG_OPCION WHERE NOMBRE = 'Administración' AND NVL(ID_OPCION_PADRE, 0) = 0 ), 1, RAWTOHEX(sys_guid()) , 1 , SYSDATE);
INSERT INTO SHM_SEG_OPCION (ID_OPCION, NOMBRE, URL, ICONO, ORDEN, ID_OPCION_PADRE, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEG_OPCION_SEQ.nextval,'Entidades Medicas','EntidadMedica/Index','<i class="far fa-circle nav-icon"></i>',2,(SELECT MAX(ID_OPCION) FROM SHM_SEG_OPCION WHERE NOMBRE = 'Administración' AND NVL(ID_OPCION_PADRE, 0) = 0 ), 1, RAWTOHEX(sys_guid()) , 1 , SYSDATE);
INSERT INTO SHM_SEG_OPCION (ID_OPCION, NOMBRE, URL, ICONO, ORDEN, ID_OPCION_PADRE, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEG_OPCION_SEQ.nextval,'Usuarios Internos','Usuario/Internos','<i class="far fa-circle nav-icon"></i>',3,(SELECT MAX(ID_OPCION) FROM SHM_SEG_OPCION WHERE NOMBRE = 'Administración' AND NVL(ID_OPCION_PADRE, 0) = 0 ), 1, RAWTOHEX(sys_guid()) , 1 , SYSDATE);
INSERT INTO SHM_SEG_OPCION (ID_OPCION, NOMBRE, URL, ICONO, ORDEN, ID_OPCION_PADRE, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEG_OPCION_SEQ.nextval,'Usuarios Externos','Usuario/Externos','<i class="far fa-circle nav-icon"></i>',4,(SELECT MAX(ID_OPCION) FROM SHM_SEG_OPCION WHERE NOMBRE = 'Administración' AND NVL(ID_OPCION_PADRE, 0) = 0 ), 1, RAWTOHEX(sys_guid()) , 1 , SYSDATE);
INSERT INTO SHM_SEG_OPCION (ID_OPCION, NOMBRE, URL, ICONO, ORDEN, ID_OPCION_PADRE, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEG_OPCION_SEQ.nextval,'Parametros','Parametro/Index','<i class="far fa-circle nav-icon"></i>',5,(SELECT MAX(ID_OPCION) FROM SHM_SEG_OPCION WHERE NOMBRE = 'Administración' AND NVL(ID_OPCION_PADRE, 0) = 0 ), 1, RAWTOHEX(sys_guid()) , 1 , SYSDATE);
INSERT INTO SHM_SEG_OPCION (ID_OPCION, NOMBRE, URL, ICONO, ORDEN, ID_OPCION_PADRE, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEG_OPCION_SEQ.nextval,'Opciones','Opcion/Index','<i class="far fa-circle nav-icon"></i>',6,(SELECT MAX(ID_OPCION) FROM SHM_SEG_OPCION WHERE NOMBRE = 'Administración' AND NVL(ID_OPCION_PADRE, 0) = 0 ), 1, RAWTOHEX(sys_guid()) , 1 , SYSDATE);
INSERT INTO SHM_SEG_OPCION (ID_OPCION, NOMBRE, URL, ICONO, ORDEN, ID_OPCION_PADRE, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEG_OPCION_SEQ.nextval,'Roles','Rol/Index','<i class="far fa-circle nav-icon"></i>',7,(SELECT MAX(ID_OPCION) FROM SHM_SEG_OPCION WHERE NOMBRE = 'Administración' AND NVL(ID_OPCION_PADRE, 0) = 0 ), 1,sys_guid() , 1 , SYSDATE);


COMMIT;

INSERT INTO SHM_SEG_USUARIO (ID_USUARIO, TIPO_USUARIO, LOGIN, PASSWORD, EMAIL, NUMERO_DOCUMENTO, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, CELULAR, ID_ENTIDAD_MEDICA, ID_ROL, 
ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) 
VALUES (SHM_SEG_USUARIO_SEQ.NEXTVAL,'I','SYSADMIN','123456','admin@compania.com','99988877','MANUEL ANTONIO','AAAAAA','LLLLLLLLL','9998887777',NULL,1, 
1, RAWTOHEX(sys_guid()),1, SYSDATE );

COMMIT;

INSERT INTO SHM_SEG_ROL_OPCION (ID_ROL, ID_OPCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) 
SELECT ( SELECT ID_ROL FROM SHM_SEG_ROL WHERE CODIGO = 'ADMINISTRADOR_SISTEMA'), ID_OPCION, 1, RAWTOHEX(sys_guid()) , 1 , SYSDATE
FROM SHM_SEG_OPCION
ORDER BY ID_OPCION;

COMMIT;

SELECT 'Registros insertados exitosamente' AS mensaje FROM DUAL;
