-- 1 Actauliza tablas
ALTER TABLE SHM_BITACORA ADD ID_ENTIDAD NUMBER;
ALTER TABLE SHM_BITACORA ADD FECHA_ACCION DATE;


ALTER TABLE SHM_PRODUCCION ADD FACTURA_FECHA_SOLICITUD DATE;
ALTER TABLE SHM_PRODUCCION ADD FACTURA_FECHA_ENVIO DATE;
ALTER TABLE SHM_PRODUCCION ADD FACTURA_FECHA_ACEPTACION DATE;
ALTER TABLE SHM_PRODUCCION ADD FACTURA_FECHA_PAGO DATE;