INSERT INTO SHM_TABLA(ID_TABLA, CODIGO, DESCRIPCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES(SHM_TABLA_SEQ.NEXTVAL,'TIPO_ENTIDAD_MEDICA','TIPO_ENTIDAD_MEDICA',1, SYS_GUID(),1, SYSDATE);
INSERT INTO SHM_TABLA(ID_TABLA, CODIGO, DESCRIPCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES(SHM_TABLA_SEQ.NEXTVAL,'TIPO_PRODUCCION','TIPO_PRODUCCION',1, SYS_GUID(),1, SYSDATE);
INSERT INTO SHM_TABLA(ID_TABLA, CODIGO, DESCRIPCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES(SHM_TABLA_SEQ.NEXTVAL,'TIPO_MEDICO','TIPO_MEDICO',1, SYS_GUID(),1, SYSDATE);
INSERT INTO SHM_TABLA(ID_TABLA, CODIGO, DESCRIPCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES(SHM_TABLA_SEQ.NEXTVAL,'TIPO_RUBRO','TIPO_RUBRO',1, SYS_GUID(),1, SYSDATE);
INSERT INTO SHM_TABLA(ID_TABLA, CODIGO, DESCRIPCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES(SHM_TABLA_SEQ.NEXTVAL,'TIPO_USUARIO','TIPO_USUARIO',1, SYS_GUID(),1, SYSDATE);
INSERT INTO SHM_TABLA(ID_TABLA, CODIGO, DESCRIPCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES(SHM_TABLA_SEQ.NEXTVAL,'ESTADO_PROCESO','ESTADO_PROCESO',1, SYS_GUID(),1, SYSDATE);
INSERT INTO SHM_TABLA(ID_TABLA, CODIGO, DESCRIPCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES(SHM_TABLA_DETALLE_SEQ.NEXTVAL,'ESTADO_COMPROBANTE','',1, SYS_GUID(),1, SYSDATE);
INSERT INTO SHM_TABLA(ID_TABLA, CODIGO, DESCRIPCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES(SHM_TABLA_DETALLE_SEQ.NEXTVAL,'ESTADO_ORDEN_PAGO','',1, SYS_GUID(),1, SYSDATE);
INSERT INTO SHM_TABLA(ID_TABLA, CODIGO, DESCRIPCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES(SHM_TABLA_DETALLE_SEQ.NEXTVAL,'ESTADO_ORDEN_PAGO_APROBACION','',1, SYS_GUID(),1, SYSDATE);
INSERT INTO SHM_TABLA(ID_TABLA, CODIGO, DESCRIPCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES(SHM_TABLA_DETALLE_SEQ.NEXTVAL,'TIPO_COMPROBANTE','',1, SYS_GUID(),1, SYSDATE);

COMMIT;

-- TIPO_ENTIDAD_MEDICA
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(1,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'1','Compañía medica',1, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(1,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'0','Medico',2, SYS_GUID(), 1, 1, SYSDATE);

-- TIPO_PRODUCCION
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(2,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'01','Crédito',1, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(2,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'02','Contado',2, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(2,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'03','Plan Familiar',3, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(2,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'04','Pronto Pago',4, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(2,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'06','Chequeo Médico',5, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(2,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'07','Anticuamiento-Crédito',6, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(2,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'08','Anticuamiento-Contado',7, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(2,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'10','Anticuamiento-Plan familiar',8, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(2,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'11','Anticuamiento-Chequeo médico',9, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(2,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'12','Servicio de Laboratorio',10, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(2,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'13','Servicio Chequeo médico',11, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(2,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'14','Anticuamiento Serv. Laboratorio',12, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(2,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'15','Anticuamiento Serv. Chequeo',13, SYS_GUID(), 1, 1, SYSDATE);

-- TIPO_MEDICO
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(3,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'01','Médico Invitado',1, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(3,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'02','Cía. Médica / Médico',2, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(3,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'03','Facturación labcore',3, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(3,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'04','Facturación Tomomedic',4, SYS_GUID(), 1, 1, SYSDATE);

-- TIPO_RUBRO
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(4,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'00','Clínica',1, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(4,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'01','Honorarios',2, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(4,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'02','Servicios',3, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(4,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'03','Todos',4, SYS_GUID(), 1, 1, SYSDATE);

-- TIPO_USUARIO
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(5,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'I','Interno',1, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(5,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'E','Externo',2, SYS_GUID(), 1, 1, SYSDATE);

-- ESTADO_PROCESO
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(6,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'FACTURA_PENDIENTE','Factura Pendiente',1, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(6,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'FACTURA_SOLICITADA','Factura Solicitada',2, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(6,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'FACTURA_ENVIADA','Factura Enviada',3, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(6,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'FACTURA_ACEPTADA','Factura Aceptada',4, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(6,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'FACTURA_ENVIADA_HHMM','Factura Enviada a HHMM',5, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(6,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'FACTURA_LIQUIDADA','Factura Liquidada',6, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(6,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'FACTURA_ORDEN_PAGO','Factura en Orden de Pago',7, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(6,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'FACTURA_PAGADA','Factura Pagada',8, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(6,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'FACTURA_DEVUELTA','Factura Devuelta',9, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(6,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'FACTURA_ANULADA','Factura Anulada',10, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(6,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'ANULADO','Anulado',11, SYS_GUID(), 1, 1, SYSDATE);

-- ESTADO_COMPROBANTE
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES((SELECT ID_TABLA FROM SHM_TABLA WHERE CODIGO = 'ESTADO_COMPROBANTE') ,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'POR_ENVIAR','Por Enviar',1, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES((SELECT ID_TABLA FROM SHM_TABLA WHERE CODIGO = 'ESTADO_COMPROBANTE') ,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'ENVIADO','Enviado',2, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES((SELECT ID_TABLA FROM SHM_TABLA WHERE CODIGO = 'ESTADO_COMPROBANTE') ,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'ACEPTADO','Aceptado',3, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES((SELECT ID_TABLA FROM SHM_TABLA WHERE CODIGO = 'ESTADO_COMPROBANTE') ,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'DEVUELTO','Devuelto',4, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES((SELECT ID_TABLA FROM SHM_TABLA WHERE CODIGO = 'ESTADO_COMPROBANTE') ,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'PAGADO','Pagado',5, SYS_GUID(), 1, 1, SYSDATE);

-- ESTADO_ORDEN_PAGO
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES((SELECT ID_TABLA FROM SHM_TABLA WHERE CODIGO = 'ESTADO_ORDEN_PAGO') ,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'APROBACION_PENDIENTE','Aprobacion Pendiente',1, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES((SELECT ID_TABLA FROM SHM_TABLA WHERE CODIGO = 'ESTADO_ORDEN_PAGO') ,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'DEVUELTO','Devuelto',2, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES((SELECT ID_TABLA FROM SHM_TABLA WHERE CODIGO = 'ESTADO_ORDEN_PAGO') ,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'APROBADO','Aprobado',3, SYS_GUID(), 1, 1, SYSDATE);

-- ESTADO_ORDEN_PAGO_APROBACION
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES((SELECT ID_TABLA FROM SHM_TABLA WHERE CODIGO = 'ESTADO_ORDEN_PAGO_APROBACION') ,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'APROBACION_PENDIENTE','Aprobacion Pendiente',1, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES((SELECT ID_TABLA FROM SHM_TABLA WHERE CODIGO = 'ESTADO_ORDEN_PAGO_APROBACION') ,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'APROBADO','Aprobado',2, SYS_GUID(), 1, 1, SYSDATE);

-- TIPO_COMPROBANTE
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES((SELECT ID_TABLA FROM SHM_TABLA WHERE CODIGO = 'TIPO_COMPROBANTE') ,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'1','Factura',1, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES((SELECT ID_TABLA FROM SHM_TABLA WHERE CODIGO = 'TIPO_COMPROBANTE') ,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'22','Recibo por Honorarios',2, SYS_GUID(), 1, 1, SYSDATE);

COMMIT;

INSERT INTO SHM_SEG_ROL (ID_ROL, CODIGO, DESCRIPCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEG_ROL_SEQ.NEXTVAL,'ADMINISTRADOR_SISTEMA','Administrador del sistema',1,sys_guid() , 1 , SYSDATE);
INSERT INTO SHM_SEG_ROL (ID_ROL, CODIGO, DESCRIPCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEG_ROL_SEQ.NEXTVAL,'COMPANIA_MEDICA','Compañía médica',1,sys_guid() , 1 , SYSDATE);
INSERT INTO SHM_SEG_ROL (ID_ROL, CODIGO, DESCRIPCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEG_ROL_SEQ.NEXTVAL,'HONORARIO_MEDICO','Honorarios medicos',1,sys_guid() , 1 , SYSDATE);
INSERT INTO SHM_SEG_ROL (ID_ROL, CODIGO, DESCRIPCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEG_ROL_SEQ.NEXTVAL,'TESORERIA','Tesorería',1,sys_guid() , 1 , SYSDATE);
INSERT INTO SHM_SEG_ROL (ID_ROL, CODIGO, DESCRIPCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEG_ROL_SEQ.NEXTVAL,'APROBADOR','Aprobador',1,sys_guid() , 1 , SYSDATE);

COMMIT;

-- SHM_PARAMETRO
INSERT INTO SHM_PARAMETRO (ID_PARAMETRO, CODIGO,DESCRIPCION, VALOR, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION, TIPO_PRAMETRO)
VALUES(SHM_PARAMETRO_SEQ.NEXTVAL, 'SHM_VALIDA_CUENTA_BANCARIA','Validación de Cuenta Bancaria en Factura', 'S',SYS_GUID() ,1, 1, SYSDATE, 'LOGICO');

INSERT INTO SHM_PARAMETRO (ID_PARAMETRO, CODIGO,DESCRIPCION, VALOR, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION, TIPO_PRAMETRO)
VALUES(SHM_PARAMETRO_SEQ.NEXTVAL, 'SHM_VALIDA_FACTURA_CONCEPTO','Validación de Concepto en Factura', 'N',SYS_GUID() ,1, 1, SYSDATE, 'LOGICO');

INSERT INTO SHM_PARAMETRO (ID_PARAMETRO, CODIGO,DESCRIPCION, VALOR, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION, TIPO_PRAMETRO)
VALUES(SHM_PARAMETRO_SEQ.NEXTVAL, 'SHM_REQUIERE_ARCHIVO_CDR', 'Obligatorio Adjuntar CDR','N',SYS_GUID() ,1, 1, SYSDATE, 'LOGICO');

INSERT INTO SHM_PARAMETRO (ID_PARAMETRO, CODIGO,DESCRIPCION, VALOR, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION, TIPO_PRAMETRO)
VALUES(SHM_PARAMETRO_SEQ.NEXTVAL, 'SHM_TIPO_ALMACENAMIENTO_ARCHIVO','2 Valores : FILE y BLOB', 'BLOB',SYS_GUID() ,1, 1, SYSDATE, 'TEXTO');

INSERT INTO SHM_PARAMETRO (ID_PARAMETRO, CODIGO,DESCRIPCION, VALOR, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION, TIPO_PRAMETRO)
VALUES(SHM_PARAMETRO_SEQ.NEXTVAL, 'SHM_COMPROBANTE_VALIDA_TIPO','Validación de tipo de comprobante', 'S',SYS_GUID() ,1, 1, SYSDATE, 'LOGICO');

INSERT INTO SHM_PARAMETRO (ID_PARAMETRO, CODIGO,DESCRIPCION, VALOR, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION, TIPO_PRAMETRO)
VALUES(SHM_PARAMETRO_SEQ.NEXTVAL, 'SHM_COMPROBANTE_VALIDA_FECHA_EMISION','Validación de fecha de emision', 'S',SYS_GUID() ,1, 1, SYSDATE, 'LOGICO');

INSERT INTO SHM_PARAMETRO (ID_PARAMETRO, CODIGO,DESCRIPCION, VALOR, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION, TIPO_PRAMETRO)
VALUES(SHM_PARAMETRO_SEQ.NEXTVAL, 'SHM_COMPROBANTE_VALIDA_SERIE','Validación de serie de comprobante', 'S',SYS_GUID() ,1, 1, SYSDATE, 'LOGICO');

INSERT INTO SHM_PARAMETRO (ID_PARAMETRO, CODIGO,DESCRIPCION, VALOR, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION, TIPO_PRAMETRO)
VALUES(SHM_PARAMETRO_SEQ.NEXTVAL, 'SHM_COMPROBANTE_VALIDA_NUMERO','Validación de numero de comprobante', 'S',SYS_GUID() ,1, 1, SYSDATE, 'LOGICO');

INSERT INTO SHM_PARAMETRO (ID_PARAMETRO, CODIGO,DESCRIPCION, VALOR, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION, TIPO_PRAMETRO)
VALUES(SHM_PARAMETRO_SEQ.NEXTVAL, 'SHM_COMPROBANTE_VALIDA_IMPORTE','Validación de importe total', 'S',SYS_GUID() ,1, 1, SYSDATE, 'LOGICO');

INSERT INTO SHM_PARAMETRO (ID_PARAMETRO, CODIGO,DESCRIPCION, VALOR, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION, TIPO_PRAMETRO)
VALUES(SHM_PARAMETRO_SEQ.NEXTVAL, 'SHM_COMPROBANTE_VALIDA_RUC_EMISOR','Validación RUC del emisor', 'S',SYS_GUID() ,1, 1, SYSDATE, 'LOGICO');

INSERT INTO SHM_PARAMETRO (ID_PARAMETRO, CODIGO,DESCRIPCION, VALOR, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION, TIPO_PRAMETRO)
VALUES(SHM_PARAMETRO_SEQ.NEXTVAL, 'SHM_COMPROBANTE_VALIDA_RUC_RECEPTOR','Validación RUC del recepsto', 'S',SYS_GUID() ,1, 1, SYSDATE, 'LOGICO');

INSERT INTO SHM_PARAMETRO (ID_PARAMETRO, CODIGO,DESCRIPCION, VALOR, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION, TIPO_PRAMETRO)
VALUES(SHM_PARAMETRO_SEQ.NEXTVAL, 'SHM_COMPROBANTE_ENVIA_HHMM','Activa envio de comprobante desde la entidad medica', 'S',SYS_GUID() ,1, 1, SYSDATE, 'LOGICO');

COMMIT;

-- SHM_SEG_USUARIO
INSERT INTO SHM_SEG_USUARIO (ID_USUARIO, TIPO_USUARIO, LOGIN, PASSWORD, EMAIL, NUMERO_DOCUMENTO, NOMBRES, APELLIDO_PATERNO, APELLIDO_MATERNO, CELULAR, ID_ENTIDAD_MEDICA, ID_ROL, 
ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) 
VALUES (SHM_SEG_USUARIO_SEQ.NEXTVAL,'I','SYSADMIN','123456','admin@compania.com','99988877','ADMIN','ADMIN','ADMIN','9998887777',NULL,1, 
1, RAWTOHEX(sys_guid()),1, SYSDATE );

COMMIT;

-- SHM_PERFIL_APROBACION
INSERT INTO SHM_PERFIL_APROBACION (ID_PERFIL_APROBACION,GRUPO_FLUJO_TRABAJO, CODIGO, DESCRIPCION, NIVEL, GUID_REGISTRO, ACTIVO, ID_USUARIO_CREADOR,FECHA_CREACION, ORDEN) 
VALUES ( 1,'FLUJO_APROBACION_ORDEN_PAGO','JEFE_SEDE','Jefe Sede','SEDE', SYS_GUID(), 1, 1, SYSDATE, 1);

INSERT INTO SHM_PERFIL_APROBACION (ID_PERFIL_APROBACION,GRUPO_FLUJO_TRABAJO, CODIGO, DESCRIPCION, NIVEL, GUID_REGISTRO, ACTIVO, ID_USUARIO_CREADOR,FECHA_CREACION, ORDEN) 
VALUES (2,'FLUJO_APROBACION_ORDEN_PAGO', 'JEFE_CORPORATIVO', 'Jefe Corporativo', 'CORP', SYS_GUID(), 1, 1, SYSDATE, 2);

COMMIT;
