DELETE SHM_TABLA_DETALLE
WHERE ID_TABLA IN (1, 2, 3, 4);

COMMIT;

-- TIPO_ENTIDAD_MEDICA
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(1,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'1','Compañía medica',1, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(1,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'0','Medico',2, SYS_GUID(), 1, 1, SYSDATE);

-- TIPO_PRODUCCION
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(2,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'01','Crédito',1, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(2,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'02','Contado',2, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(2,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'03','Plan Familiar',3, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(2,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'04','Pronto Pago',4, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(2,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'06','Chequeo Médico',5, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(2,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'07','Anticuamiento-Crédito',6, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(2,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'08','Anticuamiento-Contado',7, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(2,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'10','Anticuamiento-Plan familiar',8, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(2,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'11','Anticuamiento-Chequeo médico',9, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(2,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'12','Servicio de Laboratorio',10, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(2,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'13','Servicio Chequeo médico',11, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(2,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'14','Anticuamiento Serv. Laboratorio',12, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(2,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'15','Anticuamiento Serv. Chequeo',13, SYS_GUID(), 1, 1, SYSDATE);

-- TIPO_MEDICO
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(3,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'01','Médico Invitado',1, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(3,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'02','Cía. Médica / Médico',2, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(3,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'03','Facturación labcore',3, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(3,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'04','Facturación Tomomedic',4, SYS_GUID(), 1, 1, SYSDATE);

-- TIPO_RUBRO
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(4,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'00','Clínica',1, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(4,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'01','Honorarios',2, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(4,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'02','Servicios',3, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(4,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'03','Todos',4, SYS_GUID(), 1, 1, SYSDATE);

COMMIT;

