-- 1 Crea Vista
CREATE OR REPLACE VIEW SHM_TABLA_DETALLE_VW AS
SELECT T1.CODIGO AS CODIGO_TABLA, T2.CODIGO, T2.DESCRIPCION, T2.ORDEN, T2.ACTIVO
FROM SHM_TABLA T1, SHM_TABLA_DETALLE T2
WHERE T1.ID_TABLA = T2.ID_TABLA;