.-- 2. Registra Tabla  ESTADO_PROCESO
INSERT INTO SHM_TABLA(ID_TABLA, CODIGO, DESCRIPCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES(SHM_TABLA_DETALLE_SEQ.NEXTVAL,'ESTADO_PROCESO','ESTADO_PROCESO',1, SYS_GUID(),1, SYSDATE);


INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(6,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'PENDIENTE_FACTURA','Pendiente de Factura',1, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(6,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'FACTURA_ENVIADA','Factura Enviada',2, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(6,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'FACTURA_ACEPTADA','Factura Aceptada',3, SYS_GUID(), 1, 1, SYSDATE);

--

COMMIT;