
INSERT INTO SHM_PARAMETRO (ID_PARAMETRO, CODIGO, VALOR, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION)
VALUES(SHM_PARAMETRO_SEQ.NEXTVAL, 'SHM_VALIDA_CUENTA_BANCARIA', 'S',SYS_GUID() ,1, 1, SYSDATE);

COMMIT;