
--SELECT DISTINCT ESTADO FROM SHM_PRODUCCION
--UPDATE SHM_PRODUCCION SET ESTADO = 'FACTURA_PENDIENTE' WHERE ESTADO = 'PENDIENTE'
--SELECT * FROM SHM_TABLA_DETALLE WHERE CODIGO  = 'FACTURA_ANULADA'
.-- 2. Registra Tabla  ESTADO_PROCESO
DELETE  FROM SHM_TABLA_DETALLE WHERE ID_TABLA = 6;

INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(6,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'FACTURA_PENDIENTE','Factura Pendiente',1, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(6,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'FACTURA_SOLICITADA','Factura Solicitada',2, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(6,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'FACTURA_ENVIADA','Factura Enviada',3, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(6,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'FACTURA_ACEPTADA','Factura Aceptada',4, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(6,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'FACTURA_ENVIADA_HHMM','Factura Enviada a HHMM',5, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(6,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'FACTURA_LIQUIDADA','Factura Liquidada',6, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(6,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'FACTURA_ORDEN_PAGO','Factura en Orden de Pago',7, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(6,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'FACTURA_PAGADA','Factura Pagada',8, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(6,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'FACTURA_DEVUELTA','Factura Devuelta',9, SYS_GUID(), 1, 1, SYSDATE);
INSERT INTO SHM_TABLA_DETALLE(ID_TABLA, ID_TABLA_DETALLE, CODIGO, DESCRIPCION, ORDEN, GUID_REGISTRO, ACTIVO, ID_CREADOR, FECHA_CREACION) VALUES(6,SHM_TABLA_DETALLE_SEQ.NEXTVAL,'FACTURA_ANULADA','Factura Devuelta',10, SYS_GUID(), 1, 1, SYSDATE);


COMMIT;