DROP SEQUENCE SHM_SEG_OPCION_SEQ;
CREATE SEQUENCE SHM_SEG_OPCION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

DELETE FROM SHM_SEG_ROL_OPCION;
DELETE SHM_SEG_OPCION;

-- Agregar Insert de Opciones

INSERT INTO SHM_SEG_OPCION (ID_OPCION, NOMBRE, URL, ICONO, ORDEN, ID_OPCION_PADRE, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEG_OPCION_SEQ.nextval,'HONORARIOS','','',10,null, 1,sys_guid() , 1 , SYSDATE);
INSERT INTO SHM_SEG_OPCION (ID_OPCION, NOMBRE, URL, ICONO, ORDEN, ID_OPCION_PADRE, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEG_OPCION_SEQ.nextval,'MANTENIMIENTO','','',20,null, 1,sys_guid() , 1 , SYSDATE);

INSERT INTO SHM_SEG_OPCION (ID_OPCION, NOMBRE, URL, ICONO, ORDEN, ID_OPCION_PADRE, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEG_OPCION_SEQ.nextval,'Produccion','Produccion/Index','<i class="far fa-circle nav-icon"></i>',10,(SELECT MAX(ID_OPCION) FROM SHM_SEG_OPCION WHERE NOMBRE = 'HONORARIOS'), 1,sys_guid() , 1 , SYSDATE);
INSERT INTO SHM_SEG_OPCION (ID_OPCION, NOMBRE, URL, ICONO, ORDEN, ID_OPCION_PADRE, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEG_OPCION_SEQ.nextval,'Liquidacion','controller/accion2','<i class="far fa-circle nav-icon"></i>',20,(SELECT MAX(ID_OPCION) FROM SHM_SEG_OPCION WHERE NOMBRE = 'HONORARIOS'), 1,sys_guid() , 1 , SYSDATE);
INSERT INTO SHM_SEG_OPCION (ID_OPCION, NOMBRE, URL, ICONO, ORDEN, ID_OPCION_PADRE, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEG_OPCION_SEQ.nextval,'Orden de Pago','controller/accion3','<i class="far fa-circle nav-icon"></i>',30,(SELECT MAX(ID_OPCION) FROM SHM_SEG_OPCION WHERE NOMBRE = 'HONORARIOS'), 1,sys_guid() , 1 , SYSDATE);
INSERT INTO SHM_SEG_OPCION (ID_OPCION, NOMBRE, URL, ICONO, ORDEN, ID_OPCION_PADRE, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEG_OPCION_SEQ.nextval,'Bancos','Banco/Index','<i class="far fa-circle nav-icon"></i>',10,(SELECT MAX(ID_OPCION) FROM SHM_SEG_OPCION WHERE NOMBRE = 'MANTENIMIENTO'), 1,sys_guid() , 1 , SYSDATE);
INSERT INTO SHM_SEG_OPCION (ID_OPCION, NOMBRE, URL, ICONO, ORDEN, ID_OPCION_PADRE, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEG_OPCION_SEQ.nextval,'Entidades Medicas','EntidadMedica/Index','<i class="far fa-circle nav-icon"></i>',15,(SELECT MAX(ID_OPCION) FROM SHM_SEG_OPCION WHERE NOMBRE = 'MANTENIMIENTO'), 1,sys_guid() , 1 , SYSDATE);
INSERT INTO SHM_SEG_OPCION (ID_OPCION, NOMBRE, URL, ICONO, ORDEN, ID_OPCION_PADRE, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEG_OPCION_SEQ.nextval,'Sedes','Sede/index','<i class="far fa-circle nav-icon"></i>',20,(SELECT MAX(ID_OPCION) FROM SHM_SEG_OPCION WHERE NOMBRE = 'MANTENIMIENTO'), 1,sys_guid() , 1 , SYSDATE);
INSERT INTO SHM_SEG_OPCION (ID_OPCION, NOMBRE, URL, ICONO, ORDEN, ID_OPCION_PADRE, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEG_OPCION_SEQ.nextval,'Usuarios Internos','Usuario/Internos','<i class="far fa-circle nav-icon"></i>',25,(SELECT MAX(ID_OPCION) FROM SHM_SEG_OPCION WHERE NOMBRE = 'MANTENIMIENTO'), 1,sys_guid() , 1 , SYSDATE);
INSERT INTO SHM_SEG_OPCION (ID_OPCION, NOMBRE, URL, ICONO, ORDEN, ID_OPCION_PADRE, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEG_OPCION_SEQ.nextval,'Usuarios Externos','Usuario/Externos','<i class="far fa-circle nav-icon"></i>',30,(SELECT MAX(ID_OPCION) FROM SHM_SEG_OPCION WHERE NOMBRE = 'MANTENIMIENTO'), 1,sys_guid() , 1 , SYSDATE);
INSERT INTO SHM_SEG_OPCION (ID_OPCION, NOMBRE, URL, ICONO, ORDEN, ID_OPCION_PADRE, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEG_OPCION_SEQ.nextval,'Parametros','Parametro/Index','<i class="far fa-circle nav-icon"></i>',35,(SELECT MAX(ID_OPCION) FROM SHM_SEG_OPCION WHERE NOMBRE = 'MANTENIMIENTO'), 1,sys_guid() , 1 , SYSDATE);
INSERT INTO SHM_SEG_OPCION (ID_OPCION, NOMBRE, URL, ICONO, ORDEN, ID_OPCION_PADRE, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEG_OPCION_SEQ.nextval,'Tablas','TablaDetalle/Mantenimiento','<i class="far fa-circle nav-icon"></i>',40,(SELECT MAX(ID_OPCION) FROM SHM_SEG_OPCION WHERE NOMBRE = 'MANTENIMIENTO'), 1,sys_guid() , 1 , SYSDATE);
INSERT INTO SHM_SEG_OPCION (ID_OPCION, NOMBRE, URL, ICONO, ORDEN, ID_OPCION_PADRE, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEG_OPCION_SEQ.nextval,'Opciones','Opcion/Index','<i class="far fa-circle nav-icon"></i>',45,(SELECT MAX(ID_OPCION) FROM SHM_SEG_OPCION WHERE NOMBRE = 'MANTENIMIENTO'), 1,sys_guid() , 1 , SYSDATE);
INSERT INTO SHM_SEG_OPCION (ID_OPCION, NOMBRE, URL, ICONO, ORDEN, ID_OPCION_PADRE, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEG_OPCION_SEQ.nextval,'Roles','Rol/Index','<i class="far fa-circle nav-icon"></i>',50,(SELECT MAX(ID_OPCION) FROM SHM_SEG_OPCION WHERE NOMBRE = 'MANTENIMIENTO'), 1,sys_guid() , 1 , SYSDATE);


--- Agregar Insert de Roles para el ADMIN
INSERT INTO SHM_SEG_ROL_OPCION (ID_ROL, ID_OPCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) 
SELECT ( SELECT ID_ROL FROM SHM_SEG_ROL WHERE CODIGO = 'ADMINISTRADOR_SISTEMA'), ID_OPCION, 1, RAWTOHEX(sys_guid()) , 1 , SYSDATE
FROM SHM_SEG_OPCION
ORDER BY ID_OPCION;

COMMIT;

SELECT * FROM SHM_SEG_OPCION;
