-- ALTER SESSION SET CONTAINER = XEPDB1;
-- CONNECT shm_dev/DevPass123@//localhost:1521/XEPDB1;

-- SHM_SEDE
INSERT INTO SHM_SEDE (ID_SEDE, ID_CORPORACION, CODIGO, NOMBRE, RUC, DIRECCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEDE_SEQ.NEXTVAL,1,'01','SAN PABLO','20107463705','Av. El Polo 789, Santiago de Surco, Lima',1, sys_guid(),1, SYSDATE );
INSERT INTO SHM_SEDE (ID_SEDE, ID_CORPORACION, CODIGO, NOMBRE, RUC, DIRECCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEDE_SEQ.NEXTVAL,1,'09','SAN GABRIEL','20505018509','Av. La Marina 2955, San Miguel, Lima',1, sys_guid(),1, SYSDATE );
INSERT INTO SHM_SEDE (ID_SEDE, ID_CORPORACION, CODIGO, NOMBRE, RUC, DIRECCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEDE_SEQ.NEXTVAL,1,'04','JESUS DEL NORTE','20517738701','Av. Carlos Izaguirre 153, Independencia, Lima',1, sys_guid(),1, SYSDATE );
INSERT INTO SHM_SEDE (ID_SEDE, ID_CORPORACION, CODIGO, NOMBRE, RUC, DIRECCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEDE_SEQ.NEXTVAL,1,'03','SANTA MARTHA DEL SUR','','Av. Belisario Suarez 998, SAN JUAN DE MIRAFLORES, Lima',1, sys_guid(),1, SYSDATE );
INSERT INTO SHM_SEDE (ID_SEDE, ID_CORPORACION, CODIGO, NOMBRE, RUC, DIRECCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEDE_SEQ.NEXTVAL,1,'07','SAN JUAN BAUTISTA','','Av. Proceres de la Independencia 1764, San Juan de Lurigancho, Lima',1, sys_guid(),1, SYSDATE );
INSERT INTO SHM_SEDE (ID_SEDE, ID_CORPORACION, CODIGO, NOMBRE, RUC, DIRECCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEDE_SEQ.NEXTVAL,1,'26','CERRO COLORADO','','Av. Metropolitana, con Calle 7, Cerro Colorado, Arequipa',1, sys_guid(),1, SYSDATE );
INSERT INTO SHM_SEDE (ID_SEDE, ID_CORPORACION, CODIGO, NOMBRE, RUC, DIRECCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEDE_SEQ.NEXTVAL,1,'','CLINICA SAN PABLO TRUJILLO','','Av. Husares de  Junin 690, Urb. La Merced, Trujillo',1, sys_guid(),1, SYSDATE );
INSERT INTO SHM_SEDE (ID_SEDE, ID_CORPORACION, CODIGO, NOMBRE, RUC, DIRECCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEDE_SEQ.NEXTVAL,1,'05','SAN PABLO HUARAZ','','Jr. Huaylas 172, Huaraz',1, sys_guid(),1, SYSDATE );
INSERT INTO SHM_SEDE (ID_SEDE, ID_CORPORACION, CODIGO, NOMBRE, RUC, DIRECCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEDE_SEQ.NEXTVAL,1,'13','LA ALAMEDA','','',1, sys_guid(),1, SYSDATE );
INSERT INTO SHM_SEDE (ID_SEDE, ID_CORPORACION, CODIGO, NOMBRE, RUC, DIRECCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEDE_SEQ.NEXTVAL,1,'15','LA MERCED','','',1, sys_guid(),1, SYSDATE );
INSERT INTO SHM_SEDE (ID_SEDE, ID_CORPORACION, CODIGO, NOMBRE, RUC, DIRECCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEDE_SEQ.NEXTVAL,1,'16','PRIMAVERA','','',1, sys_guid(),1, SYSDATE );
INSERT INTO SHM_SEDE (ID_SEDE, ID_CORPORACION, CODIGO, NOMBRE, RUC, DIRECCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEDE_SEQ.NEXTVAL,1,'38','DERMOESTHETIC','','',1, sys_guid(),1, SYSDATE );
INSERT INTO SHM_SEDE (ID_SEDE, ID_CORPORACION, CODIGO, NOMBRE, RUC, DIRECCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEDE_SEQ.NEXTVAL,1,'43','MEDICENTRO LOS OLIVOS','','',1, sys_guid(),1, SYSDATE );
INSERT INTO SHM_SEDE (ID_SEDE, ID_CORPORACION, CODIGO, NOMBRE, RUC, DIRECCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEDE_SEQ.NEXTVAL,1,'45','LA VICTORIA','','',1, sys_guid(),1, SYSDATE );
INSERT INTO SHM_SEDE (ID_SEDE, ID_CORPORACION, CODIGO, NOMBRE, RUC, DIRECCION, ACTIVO, GUID_REGISTRO, ID_CREADOR, FECHA_CREACION) VALUES (SHM_SEDE_SEQ.NEXTVAL,1,'','SAN PABLO LA VICTORIA','20605554505','Av. Iquitos 600, La Victoria, Lima',1, sys_guid(),1, SYSDATE );

COMMIT;

SELECT 'Registros insertados exitosamente' AS mensaje FROM DUAL;
